export default {
  editor: {
    "editor.main_title": "Main Entities",
    "editor.bkw_section": "Balcony plant / garden PV",
    "editor.bkw_enabled": "Show BKW bubble",
    "editor.bkw_unit_kw": "Sensor reports kW instead of W",
    "editor.bkw_color_bubble": "Bubble colour",
    "editor.bkw_color_pipe": "Pipe colour",
    "editor.bkw_color_text": "Value colour",
    "editor.bkw_color_icon": "Icon colour",
    "editor.bkw_label_pos_house": "Watt label: BKW → house",
    "editor.bkw_label_pos_grid": "Watt label: BKW → grid",
    "editor.bkw_label_pos_venus": "Watt label: BKW → venus",
    "editor.bkw_donut_section": "Production ring",
    "editor.bkw_donut_enabled": "Show production ring",
    "editor.bkw_donut_produced": "Sensor: produced today (kWh)",
    "editor.bkw_donut_forecast": "Sensor: remaining forecast today (kWh)",
    "editor.bkw_donut_hint": "The ring compares what has been harvested against what is STILL expected today. The forecast sensor must carry the remaining value, not the daily total.",
    "editor.solar_section": "Solar",
    "editor.grid_section": "Grid Connection",
    "editor.battery_section": "Battery 1",
    "editor.venus_section": "Battery 2",
    "editor.side_panels_scale_hint": "Panel width and gap are taken away from the card. If less than 800 px remain, the whole visual shrinks — bubbles included.",
    "editor.side_panels_reserve": "Space taken by both panels",
    "editor.side_panels_threshold": "Card stays at full size from a window width of",
    "editor.side_panels_warn": "That is wider than most screens — the card will be scaled down.",
    "editor.power_entities_title": "Power tile sensors",
    // Label for the flatten:false entity container in the power section.
    "editor.entities": "Sensors",
    "editor.power_pulse_enabled": "Pulse on grid import",
    "editor.power_pulse_threshold": "Pulse threshold (W)",
    "editor.power_section": "Power Tile",
    "editor.power_enabled": "Enable power tile",
    "editor.power_position_hint": "Shift the tile position (in pixels, default 0). The tile measures 130 × 310 px and sits to the right of the house by default.",
    "editor.power_offset_x": "Offset X (px, + right / − left)",
    "editor.power_offset_y": "Offset Y (px, + down / − up)",
    "editor.power_entities_hint": "Only the values the card does not already know. Everything else — origin split, PV, electricity cost, colours — is picked up automatically from the bubble sensors.",
    "editor.power_autarkie": "Self-sufficiency today (%)",
    "editor.power_lg_nutzbar": "LG — usable energy left (kWh)",
    "editor.power_lg_reichweite": "LG — runtime left (h)",
    "editor.power_venus_nutzbar": "Venus — usable energy left (kWh)",
    "editor.power_venus_reichweite": "Venus — runtime left (h)",
    "editor.temp_section": "Climate (Temperature)",
    "editor.temp_enabled": "Enable climate bubble",
    "editor.temp_position_hint": "Move the panel (in pixels, default = 0).",
    "editor.temp_offset_x": "Offset X (px, + right / − left)",
    "editor.temp_offset_y": "Offset Y (px, + down / − up)",
    "editor.temp_sensors_hint": "Sensors for the thermometer columns. Leave empty to use the defaults.",
    "editor.temp_outdoor": "Outdoor temperature (current)",
    "editor.temp_indoor": "Indoor temperature (current)",
    "editor.temp_forecast_high": "Forecast daily high (outdoor)",
    "editor.temp_forecast_low": "Forecast daily low (outdoor)",
    "editor.temp_scales_hint": "Scale ranges for the column fill level.",
    "editor.temp_outdoor_min": "Outdoor scale minimum (°C)",
    "editor.temp_outdoor_max": "Outdoor scale maximum (°C)",
    "editor.temp_indoor_min": "Indoor scale minimum (°C)",
    "editor.temp_indoor_max": "Indoor scale maximum (°C)",
    "editor.temp_colors_hint": "Thermometer colors.",
    "editor.temp_outdoor_color": "Outdoor column color",
    "editor.temp_sparkline_hint": "Background history graphs in the panel (like the other bubbles).",
    "editor.temp_sparkline_indoor_title": "Indoor history (left)",
    "editor.temp_sparkline_outdoor_title": "Outdoor history (right)",
    "editor.temp_indoor_color": "Indoor column color",
    "editor.temp_marker_color": "Forecast marker color",
    "editor.consumer_1_section": "Tesla",
    "editor.consumers_section": "House",
    "editor.bubble_fallback": "Bubble {n}",
    "editor.consumer_1_donut_section": "SoC Donut (inner ring)",
    "editor.consumer_1_donut_hint": "Renders the secondary sensor value as a filled ring around the bubble. Maximum defines what 100% means (e.g. 100 for SoC %, 65 for boiler temperature °C, 200 for water level cm).",
    "editor.consumer_1_soc_donut_enable": "Enable SoC donut",
    "editor.consumer_1_soc_max": "Maximum (= 100% fill)",
    "editor.consumer_5_donut_section": "Temperature donut (inner ring)",
    "editor.consumer_5_donut_hint": "Renders the secondary sensor value (e.g. boiler temperature) as a filled ring around the bubble. Maximum defines what 100% means — typically 65 °C for a hot-water boiler.",
    "editor.consumer_5_soc_donut_enable": "Enable temperature donut",
    "editor.consumer_5_soc_max": "Maximum °C (= 100% fill)",
    "editor.consumer_5_mix_section": "Charge-mix ring (outer ring)",
    "editor.consumer_5_mix_hint": "Renders a second ring outside the BWWP bubble. Four segments (PV yellow / Battery 1 purple / Battery 2 violet / Grid red) weighted by the energy mix in the chosen period. Provide daily/monthly/yearly kWh sensors via HEIMDALL.",
    "editor.consumer_5_mix_enable": "Enable charge-mix ring",
    "editor.consumer_5_mix_pv_day": "PV share today (kWh)",
    "editor.consumer_5_mix_lg_day": "Battery 1 share today (kWh)",
    "editor.consumer_5_mix_venus_day": "Battery 2 share today (kWh)",
    "editor.consumer_5_mix_grid_day": "Grid share today (kWh)",
    "editor.consumer_5_mix_pv_month": "PV share month (kWh)",
    "editor.consumer_5_mix_lg_month": "Battery 1 share month (kWh)",
    "editor.consumer_5_mix_venus_month": "Battery 2 share month (kWh)",
    "editor.consumer_5_mix_grid_month": "Grid share month (kWh)",
    "editor.consumer_5_mix_pv_year": "PV share year (kWh)",
    "editor.consumer_5_mix_lg_year": "Battery 1 share year (kWh)",
    "editor.consumer_5_mix_venus_year": "Battery 2 share year (kWh)",
    "editor.consumer_5_mix_grid_year": "Grid share year (kWh)",
    "editor.consumer_7_donut_section": "Water-level donut (inner ring)",
    "editor.consumer_7_donut_hint": "Renders the secondary sensor value (e.g. cistern water level) as a filled ring around the bubble. Maximum defines what 100% means — typically 165 cm for a standard rainwater cistern.",
    "editor.consumer_7_soc_donut_enable": "Enable water-level donut",
    "editor.consumer_7_soc_max": "Maximum cm (= 100% fill)",
    "editor.consumer_7_mix_section": "Charge-mix ring (outer ring)",
    "editor.consumer_7_mix_hint": "Renders a second ring outside the Pumpe bubble. Four segments (PV yellow / Battery 1 purple / Battery 2 violet / Grid red) weighted by the energy mix in the chosen period. Provide daily/monthly/yearly kWh sensors via HEIMDALL.",
    "editor.consumer_7_mix_enable": "Enable charge-mix ring",
    "editor.consumer_7_mix_pv_day": "PV share today (kWh)",
    "editor.consumer_7_mix_lg_day": "Battery 1 share today (kWh)",
    "editor.consumer_7_mix_venus_day": "Battery 2 share today (kWh)",
    "editor.consumer_7_mix_grid_day": "Grid share today (kWh)",
    "editor.consumer_7_mix_pv_month": "PV share month (kWh)",
    "editor.consumer_7_mix_lg_month": "Battery 1 share month (kWh)",
    "editor.consumer_7_mix_venus_month": "Battery 2 share month (kWh)",
    "editor.consumer_7_mix_grid_month": "Grid share month (kWh)",
    "editor.consumer_7_mix_pv_year": "PV share year (kWh)",
    "editor.consumer_7_mix_lg_year": "Battery 1 share year (kWh)",
    "editor.consumer_7_mix_venus_year": "Battery 2 share year (kWh)",
    "editor.consumer_7_mix_grid_year": "Grid share year (kWh)",
    "editor.consumer_2_donut_section": "Configurable donut (inner ring)",
    "editor.consumer_2_donut_hint": "Renders the secondary sensor value as a filled ring around the bubble. Generic use — e.g. daily energy budget (max 5 kWh), remaining minutes, or other progress indicator. Maximum defines what 100% means.",
    "editor.consumer_2_soc_donut_enable": "Enable donut",
    "editor.consumer_2_soc_max": "Maximum (= 100% fill)",
    "editor.consumer_2_mix_section": "Charge-mix ring (outer ring)",
    "editor.consumer_2_mix_hint": "Renders a second ring outside the Waschen bubble. Four segments (PV yellow / Battery 1 purple / Battery 2 violet / Grid red) weighted by the energy mix in the chosen period. Provide daily/monthly/yearly kWh sensors via HEIMDALL.",
    "editor.consumer_2_mix_enable": "Enable charge-mix ring",
    "editor.consumer_2_mix_pv_day": "PV share today (kWh)",
    "editor.consumer_2_mix_lg_day": "Battery 1 share today (kWh)",
    "editor.consumer_2_mix_venus_day": "Battery 2 share today (kWh)",
    "editor.consumer_2_mix_grid_day": "Grid share today (kWh)",
    "editor.consumer_2_mix_pv_month": "PV share month (kWh)",
    "editor.consumer_2_mix_lg_month": "Battery 1 share month (kWh)",
    "editor.consumer_2_mix_venus_month": "Battery 2 share month (kWh)",
    "editor.consumer_2_mix_grid_month": "Grid share month (kWh)",
    "editor.consumer_2_mix_pv_year": "PV share year (kWh)",
    "editor.consumer_2_mix_lg_year": "Battery 1 share year (kWh)",
    "editor.consumer_2_mix_venus_year": "Battery 2 share year (kWh)",
    "editor.consumer_2_mix_grid_year": "Grid share year (kWh)",
    "editor.consumer_3_donut_section": "Configurable donut (inner ring)",
    "editor.consumer_3_donut_hint": "Renders the secondary sensor value as a filled ring around the bubble. Generic use — e.g. daily energy budget (max 5 kWh), remaining minutes, or other progress indicator. Maximum defines what 100% means.",
    "editor.consumer_3_soc_donut_enable": "Enable donut",
    "editor.consumer_3_soc_max": "Maximum (= 100% fill)",
    "editor.consumer_3_mix_section": "Charge-mix ring (outer ring)",
    "editor.consumer_3_mix_hint": "Renders a second ring outside the Trockner bubble. Four segments (PV yellow / Battery 1 purple / Battery 2 violet / Grid red) weighted by the energy mix in the chosen period. Provide daily/monthly/yearly kWh sensors via HEIMDALL.",
    "editor.consumer_3_mix_enable": "Enable charge-mix ring",
    "editor.consumer_3_mix_pv_day": "PV share today (kWh)",
    "editor.consumer_3_mix_lg_day": "Battery 1 share today (kWh)",
    "editor.consumer_3_mix_venus_day": "Battery 2 share today (kWh)",
    "editor.consumer_3_mix_grid_day": "Grid share today (kWh)",
    "editor.consumer_3_mix_pv_month": "PV share month (kWh)",
    "editor.consumer_3_mix_lg_month": "Battery 1 share month (kWh)",
    "editor.consumer_3_mix_venus_month": "Battery 2 share month (kWh)",
    "editor.consumer_3_mix_grid_month": "Grid share month (kWh)",
    "editor.consumer_3_mix_pv_year": "PV share year (kWh)",
    "editor.consumer_3_mix_lg_year": "Battery 1 share year (kWh)",
    "editor.consumer_3_mix_venus_year": "Battery 2 share year (kWh)",
    "editor.consumer_3_mix_grid_year": "Grid share year (kWh)",
    "editor.consumer_4_donut_section": "Configurable donut (inner ring)",
    "editor.consumer_4_donut_hint": "Renders the secondary sensor value as a filled ring around the bubble. Generic use — e.g. daily energy budget (max 5 kWh), remaining minutes, or other progress indicator. Maximum defines what 100% means.",
    "editor.consumer_4_soc_donut_enable": "Enable donut",
    "editor.consumer_4_soc_max": "Maximum (= 100% fill)",
    "editor.consumer_4_mix_section": "Charge-mix ring (outer ring)",
    "editor.consumer_4_mix_hint": "Renders a second ring outside the Spüler bubble. Four segments (PV yellow / Battery 1 purple / Battery 2 violet / Grid red) weighted by the energy mix in the chosen period. Provide daily/monthly/yearly kWh sensors via HEIMDALL.",
    "editor.consumer_4_mix_enable": "Enable charge-mix ring",
    "editor.consumer_4_mix_pv_day": "PV share today (kWh)",
    "editor.consumer_4_mix_lg_day": "Battery 1 share today (kWh)",
    "editor.consumer_4_mix_venus_day": "Battery 2 share today (kWh)",
    "editor.consumer_4_mix_grid_day": "Grid share today (kWh)",
    "editor.consumer_4_mix_pv_month": "PV share month (kWh)",
    "editor.consumer_4_mix_lg_month": "Battery 1 share month (kWh)",
    "editor.consumer_4_mix_venus_month": "Battery 2 share month (kWh)",
    "editor.consumer_4_mix_grid_month": "Grid share month (kWh)",
    "editor.consumer_4_mix_pv_year": "PV share year (kWh)",
    "editor.consumer_4_mix_lg_year": "Battery 1 share year (kWh)",
    "editor.consumer_4_mix_venus_year": "Battery 2 share year (kWh)",
    "editor.consumer_4_mix_grid_year": "Grid share year (kWh)",
    "editor.consumer_6_donut_section": "Configurable donut (inner ring)",
    "editor.consumer_6_donut_hint": "Renders the secondary sensor value as a filled ring around the bubble. Generic use — e.g. indoor temperature (max 30 °C), humidity (max 100 %), CO2 (max 2000 ppm) or other progress indicator. Maximum defines what 100% means.",
    "editor.consumer_6_soc_donut_enable": "Enable donut",
    "editor.consumer_6_soc_max": "Maximum (= 100% fill)",
    "editor.consumer_6_mix_section": "Charge-mix ring (outer ring)",
    "editor.consumer_6_mix_hint": "Renders a second ring outside the Klima bubble. Four segments (PV yellow / Battery 1 purple / Battery 2 violet / Grid red) weighted by the energy mix in the chosen period. Provide daily/monthly/yearly kWh sensors via HEIMDALL.",
    "editor.consumer_6_mix_enable": "Enable charge-mix ring",
    "editor.consumer_6_mix_pv_day": "PV share today (kWh)",
    "editor.consumer_6_mix_lg_day": "Battery 1 share today (kWh)",
    "editor.consumer_6_mix_venus_day": "Battery 2 share today (kWh)",
    "editor.consumer_6_mix_grid_day": "Grid share today (kWh)",
    "editor.consumer_6_mix_pv_month": "PV share month (kWh)",
    "editor.consumer_6_mix_lg_month": "Battery 1 share month (kWh)",
    "editor.consumer_6_mix_venus_month": "Battery 2 share month (kWh)",
    "editor.consumer_6_mix_grid_month": "Grid share month (kWh)",
    "editor.consumer_6_mix_pv_year": "PV share year (kWh)",
    "editor.consumer_6_mix_lg_year": "Battery 1 share year (kWh)",
    "editor.consumer_6_mix_venus_year": "Battery 2 share year (kWh)",
    "editor.consumer_6_mix_grid_year": "Grid share year (kWh)",
    "editor.consumer_1_mix_section": "Charge-mix ring (outer ring)",
    "editor.consumer_1_mix_hint": "Renders a second ring outside the bubble. Split into four segments (PV yellow / Battery 1 purple / Battery 2 violet / Grid red) weighted by the energy mix in the chosen period. Provide daily/monthly/yearly kWh sensors via HEIMDALL.",
    "editor.consumer_1_mix_enable": "Enable charge-mix ring",
    "editor.consumer_1_mix_period": "Period",
    "editor.consumer_1_mix_period_day": "Day",
    "editor.consumer_1_mix_period_month": "Month",
    "editor.consumer_1_mix_period_year": "Year",
    "editor.consumer_1_mix_ring_gap": "Gap to SoC ring (px)",
    "editor.consumer_1_mix_ring_thickness": "Mix-ring thickness (px)",
    "editor.consumer_1_mix_pv_day": "PV share today (kWh)",
    "editor.consumer_1_mix_lg_day": "Battery 1 share today (kWh)",
    "editor.consumer_1_mix_venus_day": "Battery 2 share today (kWh)",
    "editor.consumer_1_mix_grid_day": "Grid share today (kWh)",
    "editor.consumer_1_mix_pv_month": "PV share month (kWh)",
    "editor.consumer_1_mix_lg_month": "Battery 1 share month (kWh)",
    "editor.consumer_1_mix_venus_month": "Battery 2 share month (kWh)",
    "editor.consumer_1_mix_grid_month": "Grid share month (kWh)",
    "editor.consumer_1_mix_pv_year": "PV share year (kWh)",
    "editor.consumer_1_mix_lg_year": "Battery 1 share year (kWh)",
    "editor.consumer_1_mix_venus_year": "Battery 2 share year (kWh)",
    "editor.consumer_1_mix_grid_year": "Grid share year (kWh)",
    "editor.options_section": "Appearance & Options",
    "editor.side_panels_section": "Side panels",
    "editor.side_panels_enabled": "Enable side panels",
    "editor.side_panels_hint": "Embeds arbitrary HA cards to the left and right of the visualization. Requires a wide card (full column width or panel mode).",
    "editor.side_panel_width": "Panel width (px)",
    "editor.side_panel_gap": "Gap between panel and center (px)",
    "editor.side_panel_left_title": "Left column – cards",
    "editor.side_panel_right_title": "Right column – cards",
    "editor.side_panel_add_card": "Add card",
    "editor.side_panel_no_cards": "No cards yet",
    "editor.side_panel_card_yaml": "Card configuration (YAML)",
    "editor.group_sizing": "Size & Position",
    "editor.background_padding_section": "Background padding (manual)",
    "editor.background_padding_top": "Background padding top (px)",
    "editor.background_padding_bottom": "Background padding bottom (px)",
    "editor.background_padding_left": "Background padding left (px)",
    "editor.background_padding_right": "Background padding right (px)",
    "editor.group_appearance": "Visual Effects",
    "editor.group_display": "Display Behavior",
    "editor.group_debug": "Debug & Test",
    "editor.group_bg_anim": "Background Animation",
    "editor.bg_anim_hint": "Subtle animated colour layer behind the card. Only visible when the card background is opaque. Respects 'reduce motion' OS preference.",
    "editor.bg_anim_style": "Animation style",
    "editor.bg_anim_off": "Off",
    "editor.bg_anim_aurora": "Aurora (drifting colour blobs)",
    "editor.bg_anim_flow": "Slow Flow (gradient slide)",
    "editor.bg_anim_duration": "Speed (seconds per cycle)",
    "editor.bg_anim_intensity": "Intensity (opacity, 0-30%)",
    "editor.bg_anim_saturate": "Saturation (0.5 = pale, 1.5 = vivid)",
    "editor.bg_anim_colors": "Colours (4 stops)",
    "editor.bg_color_1": "Colour 1",
    "editor.bg_color_2": "Colour 2",
    "editor.bg_color_3": "Colour 3",
    "editor.bg_color_4": "Colour 4",
    "editor.group_sensors_display": "Sensors & Display",
    "editor.group_behavior": "Behavior",
    "editor.group_label_positions": "Watt label positions",
    "editor.solar_label_pos_solar_house": "Label: Solar → House",
    "editor.solar_label_pos_solar_grid": "Label: Solar → Grid (export)",
    "editor.grid_label_pos_import": "Label: Grid → House (import)",
    "editor.battery_label_pos": "Label: Battery ↔ House",
    "editor.venus_label_pos": "Label: Venus ↔ House",
    "editor.battery_soc_donut_section": "🍩 SoC donut (charge level ring)",
    "editor.battery_soc_donut_hint": "Shows the battery's state-of-charge as a ring around the bubble. Filled segment = current SoC in battery colour, rest grey. Like a smartphone battery indicator.",
    "editor.battery_soc_donut_enabled": "Enable SoC donut",
    "editor.venus_soc_donut_section": "🍩 SoC donut (charge level ring)",
    "editor.venus_soc_donut_hint": "Shows the Venus state-of-charge as a ring around the bubble. Filled segment = current SoC in Venus colour, rest grey.",
    "editor.venus_soc_donut_enabled": "Enable SoC donut",
    "editor.flow_rate_title": "Show Flow Rates (W) on pipes",
    "editor.pipe_label_size": "Pipe Label Font Size (px)",
    "editor.bubble_size": "Bubble size (px)",
    "editor.bubble_animation_threshold": "Animate above (W)",
    "editor.demo_mode": "Demo mode (1000W on all pipes)",
    "editor.card_offset_x": "Card horizontal offset (px)",
    "editor.card_offset_y": "Card vertical offset (px)",
    "editor.donut_section": "Donut Chart (Daily Mix)",
    "editor.donut_hint": "Shows the energy mix as a colored ring around the house bubble. When daily mode is enabled, the donut shows accumulated daily consumption in 4 segments (PV, LG, Venus, Grid) instead of the current live mix. Requires the \"Donut Chart\" toggle in Display & Options.",
    "editor.donut_today_mode": "Daily mode instead of live mode",
    "editor.donut_today_solar": "Daily sensor: PV → House (kWh)",
    "editor.donut_today_battery": "Daily sensor: LG → House (kWh)",
    "editor.donut_today_venus": "Daily sensor: Venus → House (kWh)",
    "editor.donut_today_grid": "Daily sensor: Grid → House (kWh)",
    "editor.consumer_enabled": "Consumer enabled",
    "editor.bubble_label_offset_x": "Watt label horizontal offset (px)",
    "editor.bubble_label_offset_y": "Watt label vertical offset (px)",
    "editor.consumer_show_power": "Show power instead of secondary sensor (big)",
    "editor.consumer_show_flow_rate": "Show watt value on pipe",
    "editor.consumer_label_offset_x": "Watt label horizontal offset (px)",
    "editor.consumer_label_offset_y": "Watt label vertical offset (px)",
    "editor.consumer_animation_threshold": "Animate above (W)",
    "editor.invert_battery": "Invert Power Value (+/-)",
    "editor.label_toggle": "Show Label in Bubble",
    "editor.side_panels_enabled": "Side panels (left/right)",
    "editor.hide_inactive": "Hide Inactive Pipes",
    "editor.entity": "Combined Battery Sensor (W)",
    "editor.label": "Label",
    "editor.icon": "Icon",
    "editor.back": "Back",
    "editor.battery_soc_label": "State of Charge (%)",
    "editor.house_total_title": "🏠 Total Consumption (optional)",
    "editor.house_sensor_label": "Sensor for House Consumption (optional)",
    "editor.house_sensor_hint": "Required to make the house icon clickable (more-details). Otherwise, the house consumption is calculated.",
    "editor.consumer_1_title": "🚗 Left (Purple)",
    "editor.consumer_2_title": "♨️ Center (Orange)",
    "editor.consumer_3_title": "🏊 Right (Cyan)",
    "editor.zoom_label": "🔍 Zoom (Standard View)",
    "editor.transparent_background": "Hide card background",
    "editor.always_color_bubbles": "Always color bubbles (even at 0 W)",
    "editor.rotation_section": "🔄 Value rotation in bubble",
    "editor.rotation_hint": "Show extra daily counters in the bubble that alternate with the live value.",
    "editor.rotation_show_live": "Show live value (e.g. current power)",
    "editor.rotation_interval_sec": "Rotation interval (seconds)",
    "editor.rotation_show_slot_1": "Show daily counter 1",
    "editor.rotation_show_slot_2": "Show daily counter 2",
    "editor.rotation_show_slot_3": "Show daily counter 3",
    "editor.rotation_slot_1_sensor": "Daily counter 1 sensor",
    "editor.rotation_slot_2_sensor": "Daily counter 2 sensor",
    "editor.rotation_slot_3_sensor": "Daily counter 3 sensor",
    "editor.rotation_slot_1_color": "Daily counter 1 color",
    "editor.rotation_slot_2_color": "Daily counter 2 color",
    "editor.rotation_slot_3_color": "Daily counter 3 color",
    "editor.grid_donut_section": "🍩 Grid donut (today's mix)",
    "editor.grid_donut_hint": "Shows today's import-to-export ratio as a ring around the grid bubble. Import share in the grid color, export share in the export color.",
    "editor.grid_donut_enabled": "Enable today's donut",
    "editor.grid_donut_import_sensor": "Daily grid import sensor (kWh)",
    "editor.grid_donut_export_sensor": "Daily grid export sensor (kWh)",
    "editor.pv_donut_section": "🍩 PV donut (forecast remaining)",
    "editor.pv_donut_hint": "Shows how much of today's forecast is still expected (like a fuel gauge). Yellow segment = still to come, grey segment = already produced. Sensor should deliver the REMAINING forecast (e.g. evcc 'today.energy' which shrinks during the day).",
    "editor.pv_donut_enabled": "Enable forecast donut",
    "editor.pv_donut_produced_sensor": "Today's production sensor (kWh)",
    "editor.pv_donut_forecast_sensor": "Remaining forecast today (kWh)",
    "editor.neon_glow": "Neon Glow",
    "editor.donut_chart": "Donut Chart (Grid/House)",
    "editor.comet_tail": "Comet Tail Effect",
    "editor.dashed_line": "Dashed Line Effect",
    "editor.tinted_background": "Tinted Background in Bubbles",
    "editor.colored_values": "Colored Text Values",
    "editor.hide_consumer_icons": "Hide Consumer Icons",
    "editor.invert_consumer": "Invert Sensor Value (+/-)",
    "editor.hide_solar_arc": "Hide top solar pipe",
    "editor.storage_enabled": "Storage enabled",
    "editor.secondary_sensor": "Secondary Sensor (display only)",
    "editor.grid_to_battery_sensor": "Grid to Battery Sensor (W, optional)",
    "editor.grid_to_battery_hint": "Optional: separate sensor for grid-to-battery flow. If empty, the value is calculated automatically.",
    "editor.grid_combined_sensor": "Combined Grid Sensor (W, Optional)",
    "editor.grid_combined_hint": "Single sensor for import AND export: positive = import, negative = export. Overrides combined import/export sensor.",
    "editor.color_picker": "Bubble Color",
    "editor.pipe_color": "Pipe Color",
    "editor.export_color": "Export Color",
    "editor.consumer_unit_kw": "Sensor reports in kW",
    "editor.show_consumer_always": "Show Consumers at zero watts",
    "editor.battery_charge_sensor": "Battery Charge Sensor (W, Optional)",
    "editor.battery_discharge_sensor": "Battery Discharge Sensor (W, Optional)",
    "editor.battery_separate_hint": "Optional: Separate sensors for charge/discharge. Override the main sensor for calculations.",
    "editor.consumer_hide_pipe": "Hide pipe at low power",
    "editor.consumer_pipe_threshold": "Pipe Threshold (Watts)",
    "editor.text_color": "Text Color",
    "editor.icon_color": "Icon Color",
    "editor.secondary_color": "Secondary",
    "editor.battery_charge_via_house": "Battery charge via house consumption",
    "editor.battery_show_power": "Show power instead of SoC",
    "editor.solar_unit_kw": "Show Solar in kW",
    "editor.grid_unit_kw": "Show Grid in kW",
    "editor.battery_unit_kw": "Show Battery in kW",
    "editor.venus_entity": "Combined Venus Sensor (W, signed)",
    "editor.venus_soc_label": "Venus State of Charge (%)",
    "editor.venus_charge_sensor": "Venus Charge Sensor (W, Optional)",
    "editor.venus_discharge_sensor": "Venus Discharge Sensor (W, Optional)",
    "editor.venus_separate_hint": "Optional: Separate sensors for charge/discharge. Override the main sensor for calculations.",
    "editor.venus_charge_via_house": "Venus charge via house consumption",
    "editor.venus_show_power": "Show power instead of SoC (Venus)",
    "editor.venus_unit_kw": "Show Venus in kW",
    "editor.invert_venus": "Invert Power Value (+/-) for Venus",
    "editor.venus_secondary_sensor": "Secondary Sensor (display only) for Venus",
    "editor.consumer_4_title": "⚡ Row 2 Left (Yellow)",
    "editor.consumer_5_title": "💡 Row 2 Right (Indigo)",
    "editor.consumer_6_title": "💡 Row 2 Outer Left (Teal)",
    "editor.consumer_7_title": "💡 Row 2 Outer Right (Pink)",

    // Moved here from the card block: these are editor strings and were
    // unreachable while they sat in the card dictionary.
    "editor.sparkline_title": "Sparkline (Background history graph)",
    "editor.sparkline_hint": "Shows the historical power trace as a mini chart in the bubble background. Data is pulled from HA history (refresh every 60 s).",
    "editor.sparkline_enabled": "Enable sparkline",
    "editor.sparkline_period": "Time window",
    "editor.sparkline_layer": "Layer (z-order)",
    "editor.sparkline_layer_back": "Back (behind donut)",
    "editor.sparkline_layer_mid": "Middle",
    "editor.sparkline_layer_front": "Front (above text)",
    "editor.sparkline_style": "Style",
    "editor.sparkline_style_area": "Area only",
    "editor.sparkline_style_line": "Line only",
    "editor.sparkline_style_arealine": "Area + line",
    "editor.sparkline_opacity": "Opacity",
    "editor.sparkline_color": "Color",
    "editor.sparkline_entity_label": "Sensor (optional)",
    "editor.sparkline_entity_hint": "Leave empty to use the bubble's main entity. Pick a different sensor (e.g. temperature, daily total) if you want to chart something other than power.",
    "editor.sparkline_debug": "Debug console output (DevTools)",
    "editor.sparkline_test_mode": "Test mode (synthetic sine data)",

    // Phase 5.68: LG charge-source mix ring (PV vs Grid)
    "editor.battery_mix_section": "Charge source (outer mix ring)",
    "editor.battery_mix_hint": "Adds a second ring around the SoC donut showing where LG's stored energy came from. For a storage bubble there are only 2 sources: PV and Grid.",
    "editor.battery_mix_enabled": "Enable charge-source ring",
    "editor.battery_mix_period": "Time period",
    "editor.battery_mix_period_day": "Day",
    "editor.battery_mix_period_month": "Month",
    "editor.battery_mix_period_year": "Year",
    "editor.battery_mix_gap": "Gap from SoC donut (px)",
    "editor.battery_mix_thickness": "Ring thickness (px)",
    "editor.battery_mix_day_section": "Daily sensors",
    "editor.battery_mix_month_section": "Monthly sensors",
    "editor.battery_mix_year_section": "Yearly sensors",
    "editor.battery_mix_pv_label": "PV → LG (kWh)",
    "editor.battery_mix_grid_label": "Grid → LG (kWh)",

    // Phase 5.70: Venus charge-source mix ring (PV vs Grid) -- identical to LG
    "editor.venus_mix_section": "Charge source (outer mix ring)",
    "editor.venus_mix_hint": "Adds a second ring around the SoC donut showing where Venus's stored energy came from. For a storage bubble there are only 2 sources: PV and Grid.",
    "editor.venus_mix_enabled": "Enable charge-source ring",
    "editor.venus_mix_period": "Time period",
    "editor.venus_mix_period_day": "Day",
    "editor.venus_mix_period_month": "Month",
    "editor.venus_mix_period_year": "Year",
    "editor.venus_mix_gap": "Gap from SoC donut (px)",
    "editor.venus_mix_thickness": "Ring thickness (px)",
    "editor.venus_mix_day_section": "Daily sensors",
    "editor.venus_mix_month_section": "Monthly sensors",
    "editor.venus_mix_year_section": "Yearly sensors",
    "editor.venus_mix_pv_label": "PV → Venus (kWh)",
    "editor.venus_mix_grid_label": "Grid → Venus (kWh)",

    // Phase 5.72: Solar PV-distribution mix ring (House / LG / Venus / Grid-export)
    "editor.solar_mix_section": "PV distribution (outer mix ring)",
    "editor.solar_mix_hint": "Adds a second ring around the PV donut showing where PV energy went: direct house consumption, LG charging, Venus charging, grid export.",
    "editor.solar_mix_enabled": "Enable PV-distribution ring",
    "editor.solar_mix_period": "Time period",
    "editor.mix_period_scope_hint": "Only the sensors for the period selected above are shown. Values for other periods stay saved.",
    "editor.solar_mix_period_day": "Day",
    "editor.solar_mix_period_month": "Month",
    "editor.solar_mix_period_year": "Year",
    "editor.solar_mix_gap": "Gap from PV donut (px)",
    "editor.solar_mix_thickness": "Ring thickness (px)",
    "editor.solar_mix_day_section": "Daily sensors",
    "editor.solar_mix_month_section": "Monthly sensors",
    "editor.solar_mix_year_section": "Yearly sensors",
    "editor.solar_mix_house_label": "PV → House (kWh)",
    "editor.solar_mix_lg_label": "PV → LG (kWh)",
    "editor.solar_mix_venus_label": "PV → Venus (kWh)",
    "editor.solar_mix_grid_label": "PV → Grid export (kWh)",

    // Phase 5.73: Grid Import/Export balance mix ring (2 segments)
    "editor.grid_mix_section": "Grid balance (outer mix ring)",
    "editor.grid_mix_hint": "Adds a second ring around the Tages-Mix donut showing the grid balance: how much was imported from the grid (red) vs exported to the grid (green) in the selected period?",
    "editor.grid_mix_enabled": "Enable grid-balance ring",
    "editor.grid_mix_period": "Time period",
    "editor.grid_mix_period_day": "Day",
    "editor.grid_mix_period_month": "Month",
    "editor.grid_mix_period_year": "Year",
    "editor.grid_mix_gap": "Gap from Tages-Mix donut (px)",
    "editor.grid_mix_thickness": "Ring thickness (px)",
    "editor.grid_mix_day_section": "Daily sensors",
    "editor.grid_mix_month_section": "Monthly sensors",
    "editor.grid_mix_year_section": "Yearly sensors",
    "editor.grid_mix_import_label": "Grid import (kWh)",
    "editor.grid_mix_export_label": "Grid export (kWh)",

    // Phase 5.74: House self-sufficiency (Autarkie) mix ring
    "editor.house_mix_section": "Self-sufficiency (outer mix ring)",
    "editor.house_mix_hint": "Adds a second ring around the consumption donut showing the self-sufficiency ratio: how much of the house consumption was self-supplied (PV + battery, green) vs drawn from the grid (red)?",
    "editor.house_mix_enabled": "Enable self-sufficiency ring",
    "editor.house_mix_period": "Time period",
    "editor.house_mix_period_day": "Day",
    "editor.house_mix_period_month": "Month",
    "editor.house_mix_period_year": "Year",
    "editor.house_mix_gap": "Gap from consumption donut (px)",
    "editor.house_mix_thickness": "Ring thickness (px)",
    "editor.house_mix_day_section": "Daily sensors",
    "editor.house_mix_month_section": "Monthly sensors",
    "editor.house_mix_year_section": "Yearly sensors",
    "editor.house_mix_self_label": "Self-supply (kWh)",
    "editor.house_mix_grid_label": "Grid import (kWh)",

    // Phase 5.80: configurable Tesla mix-ring segment colors
    "editor.consumer_1_mix_colors_section": "Ring colors per segment",
    "editor.consumer_1_mix_color_pv": "PV segment color",
    "editor.consumer_1_mix_color_lg": "LG segment color",
    "editor.consumer_1_mix_color_venus": "Venus segment color",
    "editor.consumer_1_mix_color_grid": "Grid segment color",

    // Phase 5.84: configurable mix-ring segment colors for source bubbles
    "editor.source_mix_colors_section": "Ring colors per segment",
    // Solar bubble (4 segments: house/lg/venus/grid)
    "editor.solar_mix_color_house": "House segment color",
    "editor.solar_mix_color_lg":    "LG segment color",
    "editor.solar_mix_color_venus": "Venus segment color",
    "editor.solar_mix_color_grid":  "Grid export segment color",
    // Grid bubble (2 segments: import/export)
    "editor.grid_mix_color_import": "Import segment color",
    "editor.grid_mix_color_export": "Export segment color",
    // LG (Battery) bubble (2 segments: pv/grid)
    "editor.battery_mix_color_pv":   "PV segment color",
    "editor.battery_mix_color_grid": "Grid segment color",
    // Venus bubble (2 segments: pv/grid)
    "editor.venus_mix_color_pv":   "PV segment color",
    "editor.venus_mix_color_grid": "Grid segment color",
    // House bubble (2 segments: self/grid)
    "editor.house_mix_color_self": "Self-supply color",
    "editor.house_mix_color_grid": "Grid import color",
  },
  card: {
    "card.label_solar": "Solar",
    "card.label_grid": "Grid",
    "card.label_battery": "Battery",
    "card.label_venus": "Venus",
    "card.label_house": "Consumption",
    "card.label_car": "Car",
    "card.label_heater": "Heater",
    "card.label_pool": "Pool",
    "card.label_consumer_4": "Cons. 4",
    "card.label_consumer_5": "Cons. 5",
    "card.label_import": "Import",
    "card.label_export": "Export",
  }
};
