export default {
  editor: {
    "card.label_import": "Import",
    "card.label_export": "Export",
    "editor.main_title": "Haupt Entitäten",
    "editor.bkw_section": "BKW / Garten-PV",
    "editor.bkw_enabled": "BKW-Bubble anzeigen",
    "editor.bkw_unit_kw": "Sensor liefert kW statt W",
    "editor.bkw_color_bubble": "Farbe Bubble",
    "editor.bkw_color_pipe": "Farbe Strahl",
    "editor.bkw_color_text": "Farbe Wert",
    "editor.bkw_color_icon": "Farbe Icon",
    "editor.bkw_label_pos_house": "Watt-Label: BKW → Haus",
    "editor.bkw_label_pos_grid": "Watt-Label: BKW → Netz",
    "editor.bkw_label_pos_venus": "Watt-Label: BKW → Venus",
    "editor.bkw_donut_section": "Ertragsring",
    "editor.bkw_donut_enabled": "Ertragsring anzeigen",
    "editor.bkw_donut_produced": "Sensor: Ertrag heute (kWh)",
    "editor.bkw_donut_forecast": "Sensor: Rest-Prognose heute (kWh)",
    "editor.bkw_donut_hint": "Der Ring vergleicht den bisherigen Ertrag mit dem, was heute NOCH erwartet wird. Der Prognose-Sensor muss den Restwert liefern, nicht das Tagestotal.",
    "editor.solar_section": "Solar/PV",
    "editor.grid_section": "Netz Import/Export",
    "editor.battery_section": "Batterie 1",
    "editor.venus_section": "Batterie 2",
    "editor.side_panels_scale_hint": "Panelbreite und Abstand gehen der Karte verloren. Bleiben ihr weniger als 800 px, verkleinert sich die gesamte Darstellung — die Blasen inklusive.",
    "editor.side_panels_reserve": "Platzbedarf beider Panels",
    "editor.side_panels_threshold": "Karte bleibt in voller Größe ab einer Fensterbreite von",
    "editor.side_panels_warn": "Das ist breiter als die meisten Bildschirme — die Karte wird verkleinert dargestellt.",
    "editor.power_entities_title": "Sensoren der Power-Kachel",
    "editor.power_section": "Power-Kachel",
    "editor.power_enabled": "Power-Kachel aktivieren",
    "editor.power_position_hint": "Position der Kachel verschieben (in Pixeln, Standard = 0). Die Kachel misst 130 × 310 px und sitzt standardmäßig rechts neben dem Haus.",
    "editor.power_offset_x": "Verschiebung X (px, + rechts / − links)",
    "editor.power_offset_y": "Verschiebung Y (px, + runter / − hoch)",
    "editor.power_entities_hint": "Nur die Werte, die die Karte noch nicht kennt. Alles andere — Herkunft, PV, Stromrechnung, Farben — übernimmt die Kachel automatisch aus den Sensoren der Blasen.",
    "editor.power_autarkie": "Autarkiegrad heute (%)",
    "editor.power_lg_nutzbar": "LG — nutzbare Restenergie (kWh)",
    "editor.power_lg_reichweite": "LG — Reichweite (h)",
    "editor.power_venus_nutzbar": "Venus — nutzbare Restenergie (kWh)",
    "editor.power_venus_reichweite": "Venus — Reichweite (h)",
    "editor.temp_section": "Klima (Temperatur)",
    "editor.temp_enabled": "Klima-Bubble aktivieren",
    "editor.temp_position_hint": "Position der Kachel verschieben (in Pixeln, Standard = 0).",
    "editor.temp_offset_x": "Verschiebung X (px, + rechts / − links)",
    "editor.temp_offset_y": "Verschiebung Y (px, + runter / − hoch)",
    "editor.temp_sensors_hint": "Sensoren für die Thermometer-Säulen. Leer lassen nutzt die Standard-Sensoren.",
    "editor.temp_outdoor": "Außen-Temperatur (ist)",
    "editor.temp_indoor": "Innen-Temperatur (ist)",
    "editor.temp_forecast_high": "Vorhersage Tageshoch (außen)",
    "editor.temp_forecast_low": "Vorhersage Tagestief (außen)",
    "editor.temp_scales_hint": "Skalen-Bereiche für den Füllstand der Säulen.",
    "editor.temp_outdoor_min": "Außen-Skala Minimum (°C)",
    "editor.temp_outdoor_max": "Außen-Skala Maximum (°C)",
    "editor.temp_indoor_min": "Innen-Skala Minimum (°C)",
    "editor.temp_indoor_max": "Innen-Skala Maximum (°C)",
    "editor.temp_colors_hint": "Farben der Thermometer.",
    "editor.temp_outdoor_color": "Farbe Außen-Säule",
    "editor.temp_sparkline_hint": "Verlaufsgraphen im Hintergrund der Kachel (wie bei den anderen Bubbles).",
    "editor.temp_sparkline_indoor_title": "Verlauf Innen (links)",
    "editor.temp_sparkline_outdoor_title": "Verlauf Außen (rechts)",
    "editor.temp_indoor_color": "Farbe Innen-Säule",
    "editor.temp_marker_color": "Farbe Vorhersage-Marker",
    "editor.consumer_1_section": "Tesla",
    "editor.consumers_section": "Haus",
    "editor.bubble_fallback": "Bubble {n}",
    "editor.consumer_1_donut_section": "SoC-Donut (innerer Ring)",
    "editor.consumer_1_donut_hint": "Zeigt den Wert des Zweitsensors als gefüllten Ring um die Bubble. Das Maximum legt fest, was 100% bedeutet (z.B. 100 für SoC %, 65 für Kessel-Temperatur in °C, 200 für Wasserstand in cm).",
    "editor.consumer_1_soc_donut_enable": "SoC-Donut aktivieren",
    "editor.consumer_1_soc_max": "Maximum (= 100% Füllung)",
    "editor.consumer_5_donut_section": "Temperatur-Donut (innerer Ring)",
    "editor.consumer_5_donut_hint": "Zeigt den Wert des Zweitsensors (z.B. Kesseltemperatur) als gefüllten Ring um die Bubble. Das Maximum legt fest, was 100% bedeutet -- typisch 65 °C für einen Brauchwasserkessel.",
    "editor.consumer_5_soc_donut_enable": "Temperatur-Donut aktivieren",
    "editor.consumer_5_soc_max": "Maximum °C (= 100% Füllung)",
    "editor.consumer_5_mix_section": "Lade-Mix-Ring (äußerer Ring)",
    "editor.consumer_5_mix_hint": "Zeigt einen zweiten Ring außen um die BWWP-Bubble. Vier Segmente (PV gelb / Batterie 1 lila / Batterie 2 violett / Netz rot) gewichtet nach dem Energie-Mix im gewählten Zeitraum. Sensoren als Tages-/Monats-/Jahres-kWh-Werte in HEIMDALL anlegen.",
    "editor.consumer_5_mix_enable": "Lade-Mix-Ring aktivieren",
    "editor.consumer_5_mix_pv_day": "PV-Anteil heute (kWh)",
    "editor.consumer_5_mix_lg_day": "Batterie 1-Anteil heute (kWh)",
    "editor.consumer_5_mix_venus_day": "Batterie 2-Anteil heute (kWh)",
    "editor.consumer_5_mix_grid_day": "Netz-Anteil heute (kWh)",
    "editor.consumer_5_mix_pv_month": "PV-Anteil Monat (kWh)",
    "editor.consumer_5_mix_lg_month": "Batterie 1-Anteil Monat (kWh)",
    "editor.consumer_5_mix_venus_month": "Batterie 2-Anteil Monat (kWh)",
    "editor.consumer_5_mix_grid_month": "Netz-Anteil Monat (kWh)",
    "editor.consumer_5_mix_pv_year": "PV-Anteil Jahr (kWh)",
    "editor.consumer_5_mix_lg_year": "Batterie 1-Anteil Jahr (kWh)",
    "editor.consumer_5_mix_venus_year": "Batterie 2-Anteil Jahr (kWh)",
    "editor.consumer_5_mix_grid_year": "Netz-Anteil Jahr (kWh)",
    "editor.consumer_7_donut_section": "Wasserstand-Donut (innerer Ring)",
    "editor.consumer_7_donut_hint": "Zeigt den Wert des Zweitsensors (z.B. Wasserstand im Regenschacht) als gefüllten Ring um die Bubble. Das Maximum legt fest, was 100% bedeutet -- typisch 165 cm für einen Standard-Regenschacht.",
    "editor.consumer_7_soc_donut_enable": "Wasserstand-Donut aktivieren",
    "editor.consumer_7_soc_max": "Maximum cm (= 100% Füllung)",
    "editor.consumer_7_mix_section": "Lade-Mix-Ring (äußerer Ring)",
    "editor.consumer_7_mix_hint": "Zeigt einen zweiten Ring außen um die Pumpe-Bubble. Vier Segmente (PV gelb / Batterie 1 lila / Batterie 2 violett / Netz rot) gewichtet nach dem Energie-Mix im gewählten Zeitraum. Sensoren als Tages-/Monats-/Jahres-kWh-Werte in HEIMDALL anlegen.",
    "editor.consumer_7_mix_enable": "Lade-Mix-Ring aktivieren",
    "editor.consumer_7_mix_pv_day": "PV-Anteil heute (kWh)",
    "editor.consumer_7_mix_lg_day": "Batterie 1-Anteil heute (kWh)",
    "editor.consumer_7_mix_venus_day": "Batterie 2-Anteil heute (kWh)",
    "editor.consumer_7_mix_grid_day": "Netz-Anteil heute (kWh)",
    "editor.consumer_7_mix_pv_month": "PV-Anteil Monat (kWh)",
    "editor.consumer_7_mix_lg_month": "Batterie 1-Anteil Monat (kWh)",
    "editor.consumer_7_mix_venus_month": "Batterie 2-Anteil Monat (kWh)",
    "editor.consumer_7_mix_grid_month": "Netz-Anteil Monat (kWh)",
    "editor.consumer_7_mix_pv_year": "PV-Anteil Jahr (kWh)",
    "editor.consumer_7_mix_lg_year": "Batterie 1-Anteil Jahr (kWh)",
    "editor.consumer_7_mix_venus_year": "Batterie 2-Anteil Jahr (kWh)",
    "editor.consumer_7_mix_grid_year": "Netz-Anteil Jahr (kWh)",
    "editor.consumer_2_donut_section": "Konfigurierbarer Donut (innerer Ring)",
    "editor.consumer_2_donut_hint": "Zeigt den Wert des Zweitsensors als gefüllten Ring um die Bubble. Frei einsetzbar -- z.B. Tagesverbrauch (Max 5 kWh), Restzeit-Minuten oder anderes Fortschrittsmaß. Das Maximum legt fest, was 100% bedeutet.",
    "editor.consumer_2_soc_donut_enable": "Donut aktivieren",
    "editor.consumer_2_soc_max": "Maximum (= 100% Füllung)",
    "editor.consumer_2_mix_section": "Lade-Mix-Ring (äußerer Ring)",
    "editor.consumer_2_mix_hint": "Zeigt einen zweiten Ring außen um die Waschen-Bubble. Vier Segmente (PV gelb / Batterie 1 lila / Batterie 2 violett / Netz rot) gewichtet nach dem Energie-Mix im gewählten Zeitraum. Sensoren als Tages-/Monats-/Jahres-kWh-Werte in HEIMDALL anlegen.",
    "editor.consumer_2_mix_enable": "Lade-Mix-Ring aktivieren",
    "editor.consumer_2_mix_pv_day": "PV-Anteil heute (kWh)",
    "editor.consumer_2_mix_lg_day": "Batterie 1-Anteil heute (kWh)",
    "editor.consumer_2_mix_venus_day": "Batterie 2-Anteil heute (kWh)",
    "editor.consumer_2_mix_grid_day": "Netz-Anteil heute (kWh)",
    "editor.consumer_2_mix_pv_month": "PV-Anteil Monat (kWh)",
    "editor.consumer_2_mix_lg_month": "Batterie 1-Anteil Monat (kWh)",
    "editor.consumer_2_mix_venus_month": "Batterie 2-Anteil Monat (kWh)",
    "editor.consumer_2_mix_grid_month": "Netz-Anteil Monat (kWh)",
    "editor.consumer_2_mix_pv_year": "PV-Anteil Jahr (kWh)",
    "editor.consumer_2_mix_lg_year": "Batterie 1-Anteil Jahr (kWh)",
    "editor.consumer_2_mix_venus_year": "Batterie 2-Anteil Jahr (kWh)",
    "editor.consumer_2_mix_grid_year": "Netz-Anteil Jahr (kWh)",
    "editor.consumer_3_donut_section": "Konfigurierbarer Donut (innerer Ring)",
    "editor.consumer_3_donut_hint": "Zeigt den Wert des Zweitsensors als gefüllten Ring um die Bubble. Frei einsetzbar -- z.B. Tagesverbrauch (Max 5 kWh), Restzeit-Minuten oder anderes Fortschrittsmaß. Das Maximum legt fest, was 100% bedeutet.",
    "editor.consumer_3_soc_donut_enable": "Donut aktivieren",
    "editor.consumer_3_soc_max": "Maximum (= 100% Füllung)",
    "editor.consumer_3_mix_section": "Lade-Mix-Ring (äußerer Ring)",
    "editor.consumer_3_mix_hint": "Zeigt einen zweiten Ring außen um die Trockner-Bubble. Vier Segmente (PV gelb / Batterie 1 lila / Batterie 2 violett / Netz rot) gewichtet nach dem Energie-Mix im gewählten Zeitraum. Sensoren als Tages-/Monats-/Jahres-kWh-Werte in HEIMDALL anlegen.",
    "editor.consumer_3_mix_enable": "Lade-Mix-Ring aktivieren",
    "editor.consumer_3_mix_pv_day": "PV-Anteil heute (kWh)",
    "editor.consumer_3_mix_lg_day": "Batterie 1-Anteil heute (kWh)",
    "editor.consumer_3_mix_venus_day": "Batterie 2-Anteil heute (kWh)",
    "editor.consumer_3_mix_grid_day": "Netz-Anteil heute (kWh)",
    "editor.consumer_3_mix_pv_month": "PV-Anteil Monat (kWh)",
    "editor.consumer_3_mix_lg_month": "Batterie 1-Anteil Monat (kWh)",
    "editor.consumer_3_mix_venus_month": "Batterie 2-Anteil Monat (kWh)",
    "editor.consumer_3_mix_grid_month": "Netz-Anteil Monat (kWh)",
    "editor.consumer_3_mix_pv_year": "PV-Anteil Jahr (kWh)",
    "editor.consumer_3_mix_lg_year": "Batterie 1-Anteil Jahr (kWh)",
    "editor.consumer_3_mix_venus_year": "Batterie 2-Anteil Jahr (kWh)",
    "editor.consumer_3_mix_grid_year": "Netz-Anteil Jahr (kWh)",
    "editor.consumer_4_donut_section": "Konfigurierbarer Donut (innerer Ring)",
    "editor.consumer_4_donut_hint": "Zeigt den Wert des Zweitsensors als gefüllten Ring um die Bubble. Frei einsetzbar -- z.B. Tagesverbrauch (Max 5 kWh), Restzeit-Minuten oder anderes Fortschrittsmaß. Das Maximum legt fest, was 100% bedeutet.",
    "editor.consumer_4_soc_donut_enable": "Donut aktivieren",
    "editor.consumer_4_soc_max": "Maximum (= 100% Füllung)",
    "editor.consumer_4_mix_section": "Lade-Mix-Ring (äußerer Ring)",
    "editor.consumer_4_mix_hint": "Zeigt einen zweiten Ring außen um die Spüler-Bubble. Vier Segmente (PV gelb / Batterie 1 lila / Batterie 2 violett / Netz rot) gewichtet nach dem Energie-Mix im gewählten Zeitraum. Sensoren als Tages-/Monats-/Jahres-kWh-Werte in HEIMDALL anlegen.",
    "editor.consumer_4_mix_enable": "Lade-Mix-Ring aktivieren",
    "editor.consumer_4_mix_pv_day": "PV-Anteil heute (kWh)",
    "editor.consumer_4_mix_lg_day": "Batterie 1-Anteil heute (kWh)",
    "editor.consumer_4_mix_venus_day": "Batterie 2-Anteil heute (kWh)",
    "editor.consumer_4_mix_grid_day": "Netz-Anteil heute (kWh)",
    "editor.consumer_4_mix_pv_month": "PV-Anteil Monat (kWh)",
    "editor.consumer_4_mix_lg_month": "Batterie 1-Anteil Monat (kWh)",
    "editor.consumer_4_mix_venus_month": "Batterie 2-Anteil Monat (kWh)",
    "editor.consumer_4_mix_grid_month": "Netz-Anteil Monat (kWh)",
    "editor.consumer_4_mix_pv_year": "PV-Anteil Jahr (kWh)",
    "editor.consumer_4_mix_lg_year": "Batterie 1-Anteil Jahr (kWh)",
    "editor.consumer_4_mix_venus_year": "Batterie 2-Anteil Jahr (kWh)",
    "editor.consumer_4_mix_grid_year": "Netz-Anteil Jahr (kWh)",
    "editor.consumer_6_donut_section": "Konfigurierbarer Donut (innerer Ring)",
    "editor.consumer_6_donut_hint": "Zeigt den Wert des Zweitsensors als gefüllten Ring um die Bubble. Frei einsetzbar -- z.B. Innentemperatur (Max 30 °C), Luftfeuchtigkeit (Max 100 %), CO2 (Max 2000 ppm) oder anderes Fortschrittsmaß. Das Maximum legt fest, was 100% bedeutet.",
    "editor.consumer_6_soc_donut_enable": "Donut aktivieren",
    "editor.consumer_6_soc_max": "Maximum (= 100% Füllung)",
    "editor.consumer_6_mix_section": "Lade-Mix-Ring (äußerer Ring)",
    "editor.consumer_6_mix_hint": "Zeigt einen zweiten Ring außen um die Klima-Bubble. Vier Segmente (PV gelb / Batterie 1 lila / Batterie 2 violett / Netz rot) gewichtet nach dem Energie-Mix im gewählten Zeitraum. Sensoren als Tages-/Monats-/Jahres-kWh-Werte in HEIMDALL anlegen.",
    "editor.consumer_6_mix_enable": "Lade-Mix-Ring aktivieren",
    "editor.consumer_6_mix_pv_day": "PV-Anteil heute (kWh)",
    "editor.consumer_6_mix_lg_day": "Batterie 1-Anteil heute (kWh)",
    "editor.consumer_6_mix_venus_day": "Batterie 2-Anteil heute (kWh)",
    "editor.consumer_6_mix_grid_day": "Netz-Anteil heute (kWh)",
    "editor.consumer_6_mix_pv_month": "PV-Anteil Monat (kWh)",
    "editor.consumer_6_mix_lg_month": "Batterie 1-Anteil Monat (kWh)",
    "editor.consumer_6_mix_venus_month": "Batterie 2-Anteil Monat (kWh)",
    "editor.consumer_6_mix_grid_month": "Netz-Anteil Monat (kWh)",
    "editor.consumer_6_mix_pv_year": "PV-Anteil Jahr (kWh)",
    "editor.consumer_6_mix_lg_year": "Batterie 1-Anteil Jahr (kWh)",
    "editor.consumer_6_mix_venus_year": "Batterie 2-Anteil Jahr (kWh)",
    "editor.consumer_6_mix_grid_year": "Netz-Anteil Jahr (kWh)",
    "editor.consumer_1_mix_section": "Lade-Mix-Ring (äußerer Ring)",
    "editor.consumer_1_mix_hint": "Zeigt einen zweiten Ring außen um die Bubble. Der Ring teilt sich in vier Segmente auf (PV gelb / Batterie 1 lila / Batterie 2 violett / Netz rot) gewichtet nach dem Energie-Mix im gewählten Zeitraum. Sensoren bitte als Tages-/Monats-/Jahres-kWh-Werte in HEIMDALL anlegen.",
    "editor.consumer_1_mix_enable": "Lade-Mix-Ring aktivieren",
    "editor.consumer_1_mix_period": "Zeitraum",
    "editor.consumer_1_mix_period_day": "Tag",
    "editor.consumer_1_mix_period_month": "Monat",
    "editor.consumer_1_mix_period_year": "Jahr",
    "editor.consumer_1_mix_ring_gap": "Abstand zum SoC-Ring (px)",
    "editor.consumer_1_mix_ring_thickness": "Dicke des Mix-Rings (px)",
    "editor.consumer_1_mix_pv_day": "PV-Anteil heute (kWh)",
    "editor.consumer_1_mix_lg_day": "Batterie 1-Anteil heute (kWh)",
    "editor.consumer_1_mix_venus_day": "Batterie 2-Anteil heute (kWh)",
    "editor.consumer_1_mix_grid_day": "Netz-Anteil heute (kWh)",
    "editor.consumer_1_mix_pv_month": "PV-Anteil Monat (kWh)",
    "editor.consumer_1_mix_lg_month": "Batterie 1-Anteil Monat (kWh)",
    "editor.consumer_1_mix_venus_month": "Batterie 2-Anteil Monat (kWh)",
    "editor.consumer_1_mix_grid_month": "Netz-Anteil Monat (kWh)",
    "editor.consumer_1_mix_pv_year": "PV-Anteil Jahr (kWh)",
    "editor.consumer_1_mix_lg_year": "Batterie 1-Anteil Jahr (kWh)",
    "editor.consumer_1_mix_venus_year": "Batterie 2-Anteil Jahr (kWh)",
    "editor.consumer_1_mix_grid_year": "Netz-Anteil Jahr (kWh)",
    "editor.options_section": "Darstellung & Optionen",
    "editor.side_panels_section": "Seiten-Panels",
    "editor.side_panels_enabled": "Seiten-Panels aktivieren",
    "editor.side_panels_hint": "Bettet beliebige HA-Karten links und rechts neben der Visualisierung ein. Benötigt eine breite Karte (volle Spaltenbreite oder Panel-Modus).",
    "editor.side_panel_width": "Panel-Breite (px)",
    "editor.side_panel_gap": "Abstand zwischen Panel und Mitte (px)",
    "editor.side_panel_left_title": "Linke Spalte – Karten",
    "editor.side_panel_right_title": "Rechte Spalte – Karten",
    "editor.side_panel_add_card": "Karte hinzufügen",
    "editor.side_panel_no_cards": "Noch keine Karten",
    "editor.side_panel_card_yaml": "Karten-Konfiguration (YAML)",
    "editor.group_sizing": "Größen & Position",
    "editor.background_padding_section": "Hintergrund-Padding (manuell)",
    "editor.background_padding_top": "Hintergrund-Padding oben (px)",
    "editor.background_padding_bottom": "Hintergrund-Padding unten (px)",
    "editor.background_padding_left": "Hintergrund-Padding links (px)",
    "editor.background_padding_right": "Hintergrund-Padding rechts (px)",
    "editor.group_appearance": "Erscheinungsbild",
    "editor.group_display": "Anzeige-Verhalten",
    "editor.group_debug": "Debug & Test",
    "editor.group_bg_anim": "Hintergrund-Animation",
    "editor.bg_anim_hint": "Sanfte animierte Farbverläufe im Karten-Hintergrund. Nur wirksam wenn Kartenhintergrund sichtbar ist. Respektiert 'Animationen reduzieren' im Betriebssystem.",
    "editor.bg_anim_style": "Animations-Stil",
    "editor.bg_anim_off": "Aus",
    "editor.bg_anim_aurora": "Aurora (treibende Farb-Blobs)",
    "editor.bg_anim_flow": "Slow Flow (sanfter Farbverlauf)",
    "editor.bg_anim_duration": "Geschwindigkeit (Sekunden pro Zyklus)",
    "editor.bg_anim_intensity": "Intensität (Deckkraft, 0-30%)",
    "editor.bg_anim_saturate": "Sättigung (0.5 = blass, 1.5 = kräftig)",
    "editor.bg_anim_colors": "Farben (4 Stops)",
    "editor.bg_color_1": "Farbe 1",
    "editor.bg_color_2": "Farbe 2",
    "editor.bg_color_3": "Farbe 3",
    "editor.bg_color_4": "Farbe 4",
    "editor.group_sensors_display": "Sensoren & Darstellung",
    "editor.group_behavior": "Verhalten",
    "editor.group_label_positions": "Position der Watt-Labels",
    "editor.solar_label_pos_solar_house": "Label: Solar → Haus",
    "editor.solar_label_pos_solar_grid": "Label: Solar → Netz (Einspeisung)",
    "editor.grid_label_pos_import": "Label: Netz → Haus (Bezug)",
    "editor.battery_label_pos": "Label: Batterie ↔ Haus",
    "editor.venus_label_pos": "Label: Venus ↔ Haus",
    "editor.battery_soc_donut_section": "🍩 SoC-Donut (Ladestands-Ring)",
    "editor.battery_soc_donut_hint": "Zeigt den Akku-Ladestand als Ring um die Bubble. Gefüllter Anteil = aktueller SoC in Batterie-Farbe, Rest grau. Wie eine Smartphone-Akku-Anzeige.",
    "editor.battery_soc_donut_enabled": "SoC-Donut aktivieren",
    "editor.venus_soc_donut_section": "🍩 SoC-Donut (Ladestands-Ring)",
    "editor.venus_soc_donut_hint": "Zeigt den Venus-Ladestand als Ring um die Bubble. Gefüllter Anteil = aktueller SoC in Venus-Farbe, Rest grau.",
    "editor.venus_soc_donut_enabled": "SoC-Donut aktivieren",
    "editor.flow_rate_title": "Flussraten (W) an Röhren anzeigen",
    "editor.pipe_label_size": "Schriftgröße der Watt-Labels (px)",
    "editor.bubble_size": "Bubble-Größe (px)",
    "editor.bubble_animation_threshold": "Animation erst ab (W)",
    "editor.demo_mode": "Demo-Modus (1000W an allen Pipes)",
    "editor.card_offset_x": "Card horizontal verschieben (px)",
    "editor.card_offset_y": "Card vertikal verschieben (px)",
    "editor.donut_section": "Donut-Chart (Tages-Mix)",
    "editor.donut_hint": "Zeigt den Energie-Mix als farbigen Ring um die Haus-Bubble. Bei aktiviertem Tagesmodus wird statt des aktuellen Live-Mix der kumulierte Tagesverbrauch in 4 Segmenten (PV, LG, Venus, Netz) dargestellt. Erfordert den Schalter \"Donut Chart\" in Darstellung & Optionen.",
    "editor.donut_today_mode": "Tagesmodus statt Live-Modus",
    "editor.donut_today_solar": "Tages-Sensor: PV → Haus (kWh)",
    "editor.donut_today_battery": "Tages-Sensor: LG → Haus (kWh)",
    "editor.donut_today_venus": "Tages-Sensor: Venus → Haus (kWh)",
    "editor.donut_today_grid": "Tages-Sensor: Netz → Haus (kWh)",
    "editor.consumer_enabled": "Verbraucher aktiv",
    "editor.bubble_label_offset_x": "Watt-Label horizontal verschieben (px)",
    "editor.bubble_label_offset_y": "Watt-Label vertikal verschieben (px)",
    "editor.consumer_show_power": "Zeige Leistung statt Zweitsensor (groß)",
    "editor.consumer_show_flow_rate": "Watt-Wert an Pipe anzeigen",
    "editor.consumer_label_offset_x": "Watt-Label horizontal verschieben (px)",
    "editor.consumer_label_offset_y": "Watt-Label vertikal verschieben (px)",
    "editor.consumer_animation_threshold": "Animation erst ab (W)",
    "editor.invert_battery": "Wert umkehren (+/-)",
    "editor.label_toggle": "Label im Kreis anzeigen",
    "editor.side_panels_enabled": "Seiten-Panels (links/rechts)",
    "editor.hide_inactive": "Inaktive Röhren ausblenden",
    "editor.entity": "Kombinierter Batterie Sensor (W)",
    "editor.label": "Beschriftung",
    "editor.icon": "Icon",
    "editor.back": "Zurück",
    "editor.battery_soc_label": "Ladestand (%)",
    "editor.house_total_title": "🏠 Gesamtverbrauch (optional)",
    "editor.house_sensor_label": "Sensor für Hausverbrauch (optional)",
    "editor.house_sensor_hint": "Wird benötigt, damit das Haus-Icon anklickbar ist (more-details). Ansonsten wird der Hausverbrauch berechnet.",
    "editor.consumer_1_title": "🚗 Links (Lila)",
    "editor.consumer_2_title": "♨️ Mitte (Orange)",
    "editor.consumer_3_title": "🏊 Rechts (Türkis)",
    "editor.zoom_label": "🔍 Zoom (Standard View)",
    "editor.transparent_background": "Karten-Hintergrund ausblenden",
    "editor.always_color_bubbles": "Bubbles immer farbig (auch bei 0 W)",
    "editor.rotation_section": "🔄 Wert-Rotation in Bubble",
    "editor.rotation_hint": "Zusätzliche Tageszähler in der Bubble anzeigen die abwechselnd mit dem Live-Wert eingeblendet werden.",
    "editor.rotation_show_live": "Live-Wert anzeigen (z.B. aktuelle Leistung)",
    "editor.rotation_interval_sec": "Wechsel-Intervall (Sekunden)",
    "editor.rotation_show_slot_1": "Tageszähler 1 anzeigen",
    "editor.rotation_show_slot_2": "Tageszähler 2 anzeigen",
    "editor.rotation_show_slot_3": "Tageszähler 3 anzeigen",
    "editor.rotation_slot_1_sensor": "Sensor Tageszähler 1",
    "editor.rotation_slot_2_sensor": "Sensor Tageszähler 2",
    "editor.rotation_slot_3_sensor": "Sensor Tageszähler 3",
    "editor.rotation_slot_1_color": "Farbe Tageszähler 1",
    "editor.rotation_slot_2_color": "Farbe Tageszähler 2",
    "editor.rotation_slot_3_color": "Farbe Tageszähler 3",
    "editor.grid_donut_section": "🍩 Netz-Donut (Tages-Mix)",
    "editor.grid_donut_hint": "Visualisiert das Verhältnis von Bezug zu Einspeisung des heutigen Tages als Ring um die Netz-Bubble. Bezug-Anteil in der Netz-Farbe, Einspeise-Anteil in der Export-Farbe.",
    "editor.grid_donut_enabled": "Tages-Donut aktivieren",
    "editor.grid_donut_import_sensor": "Sensor Netzbezug heute (kWh)",
    "editor.grid_donut_export_sensor": "Sensor Netzeinspeisung heute (kWh)",
    "editor.pv_donut_section": "🍩 PV-Donut (Rest-Forecast)",
    "editor.pv_donut_hint": "Zeigt wie viel vom Tages-Forecast noch zu erwarten ist (wie eine Tank-Anzeige). Gelber Anteil = noch erwartet, grauer Anteil = bereits erzeugt. Sensor liefert den Rest-Forecast (z.B. evcc 'today.energy' — der schrumpft im Tagesverlauf).",
    "editor.pv_donut_enabled": "Forecast-Donut aktivieren",
    "editor.pv_donut_produced_sensor": "Sensor heute erzeugt (kWh)",
    "editor.pv_donut_forecast_sensor": "Sensor Rest-Forecast heute (kWh)",
    "editor.neon_glow": "Neon Glow",
    "editor.donut_chart": "Donut Chart (Grid/Haus)",
    "editor.comet_tail": "Comet Tail Effect",
    "editor.dashed_line": "Dashed Line Effect",
    "editor.tinted_background": "Farbiger Hintergrund in Kreisen",
    "editor.colored_values": "Farbige Textwerte",
    "editor.hide_consumer_icons": "Icons unten ausblenden",
    "editor.invert_consumer": "Sensorwert invertieren (+/-)",
    "editor.hide_solar_arc": "Solar-Pipe (oben) ausblenden",
    "editor.storage_enabled": "Speicher aktiviert",
    "editor.secondary_sensor": "Zweiter Sensor (nur Anzeige)",
    "editor.grid_to_battery_sensor": "Netz-zu-Batterie Sensor (W, Optional)",
    "editor.grid_to_battery_hint": "Optional: separater Sensor für den Netz-zu-Batterie Fluss. Wenn leer, wird der Wert automatisch berechnet.",
    "editor.grid_combined_sensor": "Kombinierter Netz-Sensor (W, Optional)",
    "editor.grid_combined_hint": "Ein Sensor für Import UND Export: positiv = Import, negativ = Export. Überschreibt den kombinierten Import/Export Sensor.",
    "editor.color_picker": "Bubble",
    "editor.pipe_color": "Pipe",
    "editor.export_color": "Export",
    "editor.consumer_unit_kw": "Sensor meldet in kW",
    "editor.show_consumer_always": "Verbraucher bei null Watt anzeigen",
    "editor.battery_charge_sensor": "Batterie-Ladung Sensor (W, Optional)",
    "editor.battery_discharge_sensor": "Batterie-Entladung Sensor (W, Optional)",
    "editor.battery_separate_hint": "Optional: Separate Sensoren für Laden/Entladen. Überschreiben den Hauptsensor für die Berechnung.",
    "editor.consumer_hide_pipe": "Pipe bei geringer Leistung ausblenden",
    "editor.consumer_pipe_threshold": "Pipe-Schwellenwert (Watt)",
    "editor.text_color": "Text",
    "editor.icon_color": "Icon",
    "editor.secondary_color": "Secondary",
    "editor.battery_charge_via_house": "Batterie-Ladung über Hausverbrauch umleiten",
    "editor.battery_show_power": "Zeige Leistung statt SoC",
    "editor.solar_unit_kw": "Solar in kW anzeigen",
    "editor.grid_unit_kw": "Grid in kW anzeigen",
    "editor.battery_unit_kw": "Batterie in kW anzeigen",
    "editor.venus_entity": "Kombinierter Venus Sensor (W, signed)",
    "editor.venus_soc_label": "Venus Ladestand (%)",
    "editor.venus_charge_sensor": "Venus-Ladung Sensor (W, Optional)",
    "editor.venus_discharge_sensor": "Venus-Entladung Sensor (W, Optional)",
    "editor.venus_separate_hint": "Optional: Separate Sensoren für Laden/Entladen. Überschreiben den Hauptsensor für die Berechnung.",
    "editor.venus_charge_via_house": "Venus-Ladung über Hausverbrauch umleiten",
    "editor.venus_show_power": "Zeige Leistung statt SoC (Venus)",
    "editor.venus_unit_kw": "Venus in kW anzeigen",
    "editor.invert_venus": "Wert umkehren (+/-) für Venus",
    "editor.venus_secondary_sensor": "Zweiter Sensor (nur Anzeige) für Venus",
    "editor.consumer_4_title": "⚡ Reihe 2 Links (Gelb)",
    "editor.consumer_5_title": "💡 Reihe 2 Rechts (Indigo)",
    "editor.consumer_6_title": "💡 Reihe 2 Außen Links (Teal)",
    "editor.consumer_7_title": "💡 Reihe 2 Außen Rechts (Pink)",
  },
  card: {
    "card.label_solar": "Solar",
    "card.label_grid": "Netz",
    "card.label_battery": "Batterie",
    "card.label_venus": "Venus",
    "card.label_house": "Verbrauch",
    "card.label_car": "E-Auto",
    "card.label_heater": "Heizung",
    "card.label_pool": "Pool",
    "card.label_consumer_4": "Verbr. 4",
    "card.label_consumer_5": "Verbr. 5",
    "editor.sparkline_title": "Sparkline (Verlauf im Hintergrund)",
    "editor.sparkline_hint": "Zeigt den historischen Leistungsverlauf als Mini-Diagramm im Hintergrund der Bubble. Daten kommen aus der HA-History (Refresh alle 60 Sek.).",
    "editor.sparkline_enabled": "Sparkline aktivieren",
    "editor.sparkline_period": "Zeitraum",
    "editor.sparkline_layer": "Ebene (Z-Order)",
    "editor.sparkline_layer_back": "Ganz hinten (hinter Donut)",
    "editor.sparkline_layer_mid": "Mittlere Ebene",
    "editor.sparkline_layer_front": "Ganz vorne (über Text)",
    "editor.sparkline_style": "Darstellung",
    "editor.sparkline_style_area": "Nur Fläche",
    "editor.sparkline_style_line": "Nur Linie",
    "editor.sparkline_style_arealine": "Fläche + Linie",
    "editor.sparkline_opacity": "Transparenz",
    "editor.sparkline_color": "Farbe",
    "editor.sparkline_entity_label": "Sensor (optional)",
    "editor.sparkline_entity_hint": "Wenn leer, wird der Hauptsensor der Bubble verwendet. Wähle einen anderen Sensor (z.B. Temperatur, Tagesverbrauch), wenn Du etwas anderes als Leistung im Verlauf sehen möchtest.",
    "editor.sparkline_debug": "Debug-Konsolen-Ausgabe (DevTools)",
    "editor.sparkline_test_mode": "Test-Modus (synthetische Sinus-Daten)",

    // Phase 5.68: LG charge-source mix ring (PV vs Grid)
    "editor.battery_mix_section": "Lade-Herkunft (Mix-Ring außen)",
    "editor.battery_mix_hint": "Zeigt um die SoC-Donut herum einen zweiten Ring an, der angibt aus welchen Quellen LG geladen wurde. Bei einem Speicher gibt es nur 2 Quellen: PV und Netz.",
    "editor.battery_mix_enabled": "Lade-Herkunfts-Ring aktivieren",
    "editor.battery_mix_period": "Zeitraum",
    "editor.battery_mix_period_day": "Tag",
    "editor.battery_mix_period_month": "Monat",
    "editor.battery_mix_period_year": "Jahr",
    "editor.battery_mix_gap": "Abstand zur SoC-Donut (px)",
    "editor.battery_mix_thickness": "Ring-Dicke (px)",
    "editor.battery_mix_day_section": "Tages-Sensoren",
    "editor.battery_mix_month_section": "Monats-Sensoren",
    "editor.battery_mix_year_section": "Jahres-Sensoren",
    "editor.battery_mix_pv_label": "PV → LG (kWh)",
    "editor.battery_mix_grid_label": "Netz → LG (kWh)",

    // Phase 5.70: Venus charge-source mix ring (PV vs Grid) -- identical to LG
    "editor.venus_mix_section": "Lade-Herkunft (Mix-Ring außen)",
    "editor.venus_mix_hint": "Zeigt um die SoC-Donut herum einen zweiten Ring an, der angibt aus welchen Quellen Venus geladen wurde. Bei einem Speicher gibt es nur 2 Quellen: PV und Netz.",
    "editor.venus_mix_enabled": "Lade-Herkunfts-Ring aktivieren",
    "editor.venus_mix_period": "Zeitraum",
    "editor.venus_mix_period_day": "Tag",
    "editor.venus_mix_period_month": "Monat",
    "editor.venus_mix_period_year": "Jahr",
    "editor.venus_mix_gap": "Abstand zur SoC-Donut (px)",
    "editor.venus_mix_thickness": "Ring-Dicke (px)",
    "editor.venus_mix_day_section": "Tages-Sensoren",
    "editor.venus_mix_month_section": "Monats-Sensoren",
    "editor.venus_mix_year_section": "Jahres-Sensoren",
    "editor.venus_mix_pv_label": "PV → Venus (kWh)",
    "editor.venus_mix_grid_label": "Netz → Venus (kWh)",

    // Phase 5.72: Solar PV-distribution mix ring (Haus / LG / Venus / Netz-Export)
    "editor.solar_mix_section": "PV-Verteilung (Mix-Ring außen)",
    "editor.solar_mix_hint": "Zeigt um den PV-Donut herum einen zweiten Ring an, der angibt wohin die PV-Energie geflossen ist: Direktverbrauch Haus, LG-Ladung, Venus-Ladung, Netz-Export.",
    "editor.solar_mix_enabled": "PV-Verteilungs-Ring aktivieren",
    "editor.solar_mix_period": "Zeitraum",
    "editor.solar_mix_period_day": "Tag",
    "editor.solar_mix_period_month": "Monat",
    "editor.solar_mix_period_year": "Jahr",
    "editor.solar_mix_gap": "Abstand zur PV-Donut (px)",
    "editor.solar_mix_thickness": "Ring-Dicke (px)",
    "editor.solar_mix_day_section": "Tages-Sensoren",
    "editor.solar_mix_month_section": "Monats-Sensoren",
    "editor.solar_mix_year_section": "Jahres-Sensoren",
    "editor.solar_mix_house_label": "PV → Haus (kWh)",
    "editor.solar_mix_lg_label": "PV → LG (kWh)",
    "editor.solar_mix_venus_label": "PV → Venus (kWh)",
    "editor.solar_mix_grid_label": "PV → Netz Export (kWh)",

    // Phase 5.73: Grid Import/Export balance mix ring (2 Segmente Import vs Export)
    "editor.grid_mix_section": "Netz-Bilanz (Mix-Ring außen)",
    "editor.grid_mix_hint": "Zeigt um den Tages-Mix-Donut herum einen zweiten Ring an, der die Netz-Bilanz visualisiert: wie viel wurde im gewählten Zeitraum aus dem Netz bezogen (rot) und wie viel ins Netz eingespeist (grün)?",
    "editor.grid_mix_enabled": "Netz-Bilanz-Ring aktivieren",
    "editor.grid_mix_period": "Zeitraum",
    "editor.grid_mix_period_day": "Tag",
    "editor.grid_mix_period_month": "Monat",
    "editor.grid_mix_period_year": "Jahr",
    "editor.grid_mix_gap": "Abstand zur Tages-Mix-Donut (px)",
    "editor.grid_mix_thickness": "Ring-Dicke (px)",
    "editor.grid_mix_day_section": "Tages-Sensoren",
    "editor.grid_mix_month_section": "Monats-Sensoren",
    "editor.grid_mix_year_section": "Jahres-Sensoren",
    "editor.grid_mix_import_label": "Netz Import (kWh)",
    "editor.grid_mix_export_label": "Netz Export (kWh)",

    // Phase 5.74: House self-sufficiency (Autarkie) mix ring
    "editor.house_mix_section": "Autarkie (Mix-Ring außen)",
    "editor.house_mix_hint": "Zeigt um den Verbrauchs-Donut herum einen zweiten Ring an, der den Autarkiegrad visualisiert: wie viel des Hausverbrauchs wurde selbst erzeugt (PV + Speicher, grün) und wie viel aus dem Netz bezogen (rot)?",
    "editor.house_mix_enabled": "Autarkie-Ring aktivieren",
    "editor.house_mix_period": "Zeitraum",
    "editor.house_mix_period_day": "Tag",
    "editor.house_mix_period_month": "Monat",
    "editor.house_mix_period_year": "Jahr",
    "editor.house_mix_gap": "Abstand zum Verbrauchs-Donut (px)",
    "editor.house_mix_thickness": "Ring-Dicke (px)",
    "editor.house_mix_day_section": "Tages-Sensoren",
    "editor.house_mix_month_section": "Monats-Sensoren",
    "editor.house_mix_year_section": "Jahres-Sensoren",
    "editor.house_mix_self_label": "Eigenversorgung (kWh)",
    "editor.house_mix_grid_label": "Netzbezug (kWh)",

    // Phase 5.80: configurable Tesla mix-ring segment colors
    "editor.consumer_1_mix_colors_section": "Ring-Farben pro Segment",
    "editor.consumer_1_mix_color_pv": "Farbe PV-Anteil",
    "editor.consumer_1_mix_color_lg": "Farbe LG-Anteil",
    "editor.consumer_1_mix_color_venus": "Farbe Venus-Anteil",
    "editor.consumer_1_mix_color_grid": "Farbe Netz-Anteil",

    // Phase 5.84: configurable mix-ring segment colors for source bubbles
    "editor.source_mix_colors_section": "Ring-Farben pro Segment",
    // Solar bubble (4 segments: house/lg/venus/grid)
    "editor.solar_mix_color_house": "Farbe Haus-Anteil",
    "editor.solar_mix_color_lg":    "Farbe LG-Anteil",
    "editor.solar_mix_color_venus": "Farbe Venus-Anteil",
    "editor.solar_mix_color_grid":  "Farbe Netz-Export-Anteil",
    // Grid bubble (2 segments: import/export)
    "editor.grid_mix_color_import": "Farbe Bezug-Anteil",
    "editor.grid_mix_color_export": "Farbe Einspeisung-Anteil",
    // LG (Battery) bubble (2 segments: pv/grid)
    "editor.battery_mix_color_pv":   "Farbe PV-Anteil",
    "editor.battery_mix_color_grid": "Farbe Netz-Anteil",
    // Venus bubble (2 segments: pv/grid)
    "editor.venus_mix_color_pv":   "Farbe PV-Anteil",
    "editor.venus_mix_color_grid": "Farbe Netz-Anteil",
    // House bubble (2 segments: self/grid)
    "editor.house_mix_color_self": "Farbe Eigenversorgung",
    "editor.house_mix_color_grid": "Farbe Netzbezug",
  }
};
