export default {
  editor: {
    "card.label_import": "Import",
    "card.label_export": "Export",
    "editor.main_title": "Main Entities",
    "editor.solar_section": "Solar",
    "editor.grid_section": "Grid Connection",
    "editor.battery_section": "Battery 1",
    "editor.venus_section": "Battery 2",
    "editor.consumer_1_section": "Tesla",
    "editor.consumers_section": "House",
    "editor.bubble_fallback": "Bubble {n}",
    "editor.consumer_1_donut_section": "SoC Donut (inner ring)",
    "editor.consumer_1_donut_hint": "Renders the secondary sensor value as a filled ring around the bubble. Maximum defines what 100% means (e.g. 100 for SoC %, 65 for boiler temperature °C, 200 for water level cm).",
    "editor.consumer_1_soc_donut_enable": "Enable SoC donut",
    "editor.consumer_1_soc_max": "Maximum (= 100% fill)",
    "editor.consumer_5_donut_section": "Temperature donut (inner ring)",
    "editor.consumer_5_donut_hint": "Renders the secondary sensor value (e.g. boiler temperature) as a filled ring around the bubble. Maximum defines what 100% means — typically 65 °C for a hot-water boiler.",
    "editor.consumer_5_soc_donut_enable": "Enable temperature donut",
    "editor.consumer_5_soc_max": "Maximum °C (= 100% fill)",
    "editor.consumer_5_mix_section": "Charge-mix ring (outer ring)",
    "editor.consumer_5_mix_hint": "Renders a second ring outside the BWWP bubble. Four segments (PV yellow / Battery 1 purple / Battery 2 violet / Grid red) weighted by the energy mix in the chosen period. Provide daily/monthly/yearly kWh sensors via HEIMDALL.",
    "editor.consumer_5_mix_enable": "Enable charge-mix ring",
    "editor.consumer_5_mix_pv_day": "PV share today (kWh)",
    "editor.consumer_5_mix_lg_day": "Battery 1 share today (kWh)",
    "editor.consumer_5_mix_venus_day": "Battery 2 share today (kWh)",
    "editor.consumer_5_mix_grid_day": "Grid share today (kWh)",
    "editor.consumer_5_mix_pv_month": "PV share month (kWh)",
    "editor.consumer_5_mix_lg_month": "Battery 1 share month (kWh)",
    "editor.consumer_5_mix_venus_month": "Battery 2 share month (kWh)",
    "editor.consumer_5_mix_grid_month": "Grid share month (kWh)",
    "editor.consumer_5_mix_pv_year": "PV share year (kWh)",
    "editor.consumer_5_mix_lg_year": "Battery 1 share year (kWh)",
    "editor.consumer_5_mix_venus_year": "Battery 2 share year (kWh)",
    "editor.consumer_5_mix_grid_year": "Grid share year (kWh)",
    "editor.consumer_7_donut_section": "Water-level donut (inner ring)",
    "editor.consumer_7_donut_hint": "Renders the secondary sensor value (e.g. cistern water level) as a filled ring around the bubble. Maximum defines what 100% means — typically 165 cm for a standard rainwater cistern.",
    "editor.consumer_7_soc_donut_enable": "Enable water-level donut",
    "editor.consumer_7_soc_max": "Maximum cm (= 100% fill)",
    "editor.consumer_7_mix_section": "Charge-mix ring (outer ring)",
    "editor.consumer_7_mix_hint": "Renders a second ring outside the Pumpe bubble. Four segments (PV yellow / Battery 1 purple / Battery 2 violet / Grid red) weighted by the energy mix in the chosen period. Provide daily/monthly/yearly kWh sensors via HEIMDALL.",
    "editor.consumer_7_mix_enable": "Enable charge-mix ring",
    "editor.consumer_7_mix_pv_day": "PV share today (kWh)",
    "editor.consumer_7_mix_lg_day": "Battery 1 share today (kWh)",
    "editor.consumer_7_mix_venus_day": "Battery 2 share today (kWh)",
    "editor.consumer_7_mix_grid_day": "Grid share today (kWh)",
    "editor.consumer_7_mix_pv_month": "PV share month (kWh)",
    "editor.consumer_7_mix_lg_month": "Battery 1 share month (kWh)",
    "editor.consumer_7_mix_venus_month": "Battery 2 share month (kWh)",
    "editor.consumer_7_mix_grid_month": "Grid share month (kWh)",
    "editor.consumer_7_mix_pv_year": "PV share year (kWh)",
    "editor.consumer_7_mix_lg_year": "Battery 1 share year (kWh)",
    "editor.consumer_7_mix_venus_year": "Battery 2 share year (kWh)",
    "editor.consumer_7_mix_grid_year": "Grid share year (kWh)",
    "editor.consumer_2_donut_section": "Configurable donut (inner ring)",
    "editor.consumer_2_donut_hint": "Renders the secondary sensor value as a filled ring around the bubble. Generic use — e.g. daily energy budget (max 5 kWh), remaining minutes, or other progress indicator. Maximum defines what 100% means.",
    "editor.consumer_2_soc_donut_enable": "Enable donut",
    "editor.consumer_2_soc_max": "Maximum (= 100% fill)",
    "editor.consumer_2_mix_section": "Charge-mix ring (outer ring)",
    "editor.consumer_2_mix_hint": "Renders a second ring outside the Waschen bubble. Four segments (PV yellow / Battery 1 purple / Battery 2 violet / Grid red) weighted by the energy mix in the chosen period. Provide daily/monthly/yearly kWh sensors via HEIMDALL.",
    "editor.consumer_2_mix_enable": "Enable charge-mix ring",
    "editor.consumer_2_mix_pv_day": "PV share today (kWh)",
    "editor.consumer_2_mix_lg_day": "Battery 1 share today (kWh)",
    "editor.consumer_2_mix_venus_day": "Battery 2 share today (kWh)",
    "editor.consumer_2_mix_grid_day": "Grid share today (kWh)",
    "editor.consumer_2_mix_pv_month": "PV share month (kWh)",
    "editor.consumer_2_mix_lg_month": "Battery 1 share month (kWh)",
    "editor.consumer_2_mix_venus_month": "Battery 2 share month (kWh)",
    "editor.consumer_2_mix_grid_month": "Grid share month (kWh)",
    "editor.consumer_2_mix_pv_year": "PV share year (kWh)",
    "editor.consumer_2_mix_lg_year": "Battery 1 share year (kWh)",
    "editor.consumer_2_mix_venus_year": "Battery 2 share year (kWh)",
    "editor.consumer_2_mix_grid_year": "Grid share year (kWh)",
    "editor.consumer_3_donut_section": "Configurable donut (inner ring)",
    "editor.consumer_3_donut_hint": "Renders the secondary sensor value as a filled ring around the bubble. Generic use — e.g. daily energy budget (max 5 kWh), remaining minutes, or other progress indicator. Maximum defines what 100% means.",
    "editor.consumer_3_soc_donut_enable": "Enable donut",
    "editor.consumer_3_soc_max": "Maximum (= 100% fill)",
    "editor.consumer_3_mix_section": "Charge-mix ring (outer ring)",
    "editor.consumer_3_mix_hint": "Renders a second ring outside the Trockner bubble. Four segments (PV yellow / Battery 1 purple / Battery 2 violet / Grid red) weighted by the energy mix in the chosen period. Provide daily/monthly/yearly kWh sensors via HEIMDALL.",
    "editor.consumer_3_mix_enable": "Enable charge-mix ring",
    "editor.consumer_3_mix_pv_day": "PV share today (kWh)",
    "editor.consumer_3_mix_lg_day": "Battery 1 share today (kWh)",
    "editor.consumer_3_mix_venus_day": "Battery 2 share today (kWh)",
    "editor.consumer_3_mix_grid_day": "Grid share today (kWh)",
    "editor.consumer_3_mix_pv_month": "PV share month (kWh)",
    "editor.consumer_3_mix_lg_month": "Battery 1 share month (kWh)",
    "editor.consumer_3_mix_venus_month": "Battery 2 share month (kWh)",
    "editor.consumer_3_mix_grid_month": "Grid share month (kWh)",
    "editor.consumer_3_mix_pv_year": "PV share year (kWh)",
    "editor.consumer_3_mix_lg_year": "Battery 1 share year (kWh)",
    "editor.consumer_3_mix_venus_year": "Battery 2 share year (kWh)",
    "editor.consumer_3_mix_grid_year": "Grid share year (kWh)",
    "editor.consumer_4_donut_section": "Configurable donut (inner ring)",
    "editor.consumer_4_donut_hint": "Renders the secondary sensor value as a filled ring around the bubble. Generic use — e.g. daily energy budget (max 5 kWh), remaining minutes, or other progress indicator. Maximum defines what 100% means.",
    "editor.consumer_4_soc_donut_enable": "Enable donut",
    "editor.consumer_4_soc_max": "Maximum (= 100% fill)",
    "editor.consumer_4_mix_section": "Charge-mix ring (outer ring)",
    "editor.consumer_4_mix_hint": "Renders a second ring outside the Spüler bubble. Four segments (PV yellow / Battery 1 purple / Battery 2 violet / Grid red) weighted by the energy mix in the chosen period. Provide daily/monthly/yearly kWh sensors via HEIMDALL.",
    "editor.consumer_4_mix_enable": "Enable charge-mix ring",
    "editor.consumer_4_mix_pv_day": "PV share today (kWh)",
    "editor.consumer_4_mix_lg_day": "Battery 1 share today (kWh)",
    "editor.consumer_4_mix_venus_day": "Battery 2 share today (kWh)",
    "editor.consumer_4_mix_grid_day": "Grid share today (kWh)",
    "editor.consumer_4_mix_pv_month": "PV share month (kWh)",
    "editor.consumer_4_mix_lg_month": "Battery 1 share month (kWh)",
    "editor.consumer_4_mix_venus_month": "Battery 2 share month (kWh)",
    "editor.consumer_4_mix_grid_month": "Grid share month (kWh)",
    "editor.consumer_4_mix_pv_year": "PV share year (kWh)",
    "editor.consumer_4_mix_lg_year": "Battery 1 share year (kWh)",
    "editor.consumer_4_mix_venus_year": "Battery 2 share year (kWh)",
    "editor.consumer_4_mix_grid_year": "Grid share year (kWh)",
    "editor.consumer_6_donut_section": "Configurable donut (inner ring)",
    "editor.consumer_6_donut_hint": "Renders the secondary sensor value as a filled ring around the bubble. Generic use — e.g. indoor temperature (max 30 °C), humidity (max 100 %), CO2 (max 2000 ppm) or other progress indicator. Maximum defines what 100% means.",
    "editor.consumer_6_soc_donut_enable": "Enable donut",
    "editor.consumer_6_soc_max": "Maximum (= 100% fill)",
    "editor.consumer_6_mix_section": "Charge-mix ring (outer ring)",
    "editor.consumer_6_mix_hint": "Renders a second ring outside the Klima bubble. Four segments (PV yellow / Battery 1 purple / Battery 2 violet / Grid red) weighted by the energy mix in the chosen period. Provide daily/monthly/yearly kWh sensors via HEIMDALL.",
    "editor.consumer_6_mix_enable": "Enable charge-mix ring",
    "editor.consumer_6_mix_pv_day": "PV share today (kWh)",
    "editor.consumer_6_mix_lg_day": "Battery 1 share today (kWh)",
    "editor.consumer_6_mix_venus_day": "Battery 2 share today (kWh)",
    "editor.consumer_6_mix_grid_day": "Grid share today (kWh)",
    "editor.consumer_6_mix_pv_month": "PV share month (kWh)",
    "editor.consumer_6_mix_lg_month": "Battery 1 share month (kWh)",
    "editor.consumer_6_mix_venus_month": "Battery 2 share month (kWh)",
    "editor.consumer_6_mix_grid_month": "Grid share month (kWh)",
    "editor.consumer_6_mix_pv_year": "PV share year (kWh)",
    "editor.consumer_6_mix_lg_year": "Battery 1 share year (kWh)",
    "editor.consumer_6_mix_venus_year": "Battery 2 share year (kWh)",
    "editor.consumer_6_mix_grid_year": "Grid share year (kWh)",
    "editor.consumer_1_mix_section": "Charge-mix ring (outer ring)",
    "editor.consumer_1_mix_hint": "Renders a second ring outside the bubble. Split into four segments (PV yellow / Battery 1 purple / Battery 2 violet / Grid red) weighted by the energy mix in the chosen period. Provide daily/monthly/yearly kWh sensors via HEIMDALL.",
    "editor.consumer_1_mix_enable": "Enable charge-mix ring",
    "editor.consumer_1_mix_period": "Period",
    "editor.consumer_1_mix_period_day": "Day",
    "editor.consumer_1_mix_period_month": "Month",
    "editor.consumer_1_mix_period_year": "Year",
    "editor.consumer_1_mix_ring_gap": "Gap to SoC ring (px)",
    "editor.consumer_1_mix_ring_thickness": "Mix-ring thickness (px)",
    "editor.consumer_1_mix_pv_day": "PV share today (kWh)",
    "editor.consumer_1_mix_lg_day": "Battery 1 share today (kWh)",
    "editor.consumer_1_mix_venus_day": "Battery 2 share today (kWh)",
    "editor.consumer_1_mix_grid_day": "Grid share today (kWh)",
    "editor.consumer_1_mix_pv_month": "PV share month (kWh)",
    "editor.consumer_1_mix_lg_month": "Battery 1 share month (kWh)",
    "editor.consumer_1_mix_venus_month": "Battery 2 share month (kWh)",
    "editor.consumer_1_mix_grid_month": "Grid share month (kWh)",
    "editor.consumer_1_mix_pv_year": "PV share year (kWh)",
    "editor.consumer_1_mix_lg_year": "Battery 1 share year (kWh)",
    "editor.consumer_1_mix_venus_year": "Battery 2 share year (kWh)",
    "editor.consumer_1_mix_grid_year": "Grid share year (kWh)",
    "editor.options_section": "Appearance & Options",
    "editor.group_sizing": "Size & Position",
    "editor.background_padding_section": "Background padding (manual)",
    "editor.background_padding_top": "Background padding top (px)",
    "editor.background_padding_bottom": "Background padding bottom (px)",
    "editor.background_padding_left": "Background padding left (px)",
    "editor.background_padding_right": "Background padding right (px)",
    "editor.group_appearance": "Visual Effects",
    "editor.group_display": "Display Behavior",
    "editor.group_debug": "Debug & Test",
    "editor.group_bg_anim": "Background Animation",
    "editor.bg_anim_hint": "Subtle animated colour layer behind the card. Only visible when the card background is opaque. Respects 'reduce motion' OS preference.",
    "editor.bg_anim_style": "Animation style",
    "editor.bg_anim_off": "Off",
    "editor.bg_anim_aurora": "Aurora (drifting colour blobs)",
    "editor.bg_anim_flow": "Slow Flow (gradient slide)",
    "editor.bg_anim_duration": "Speed (seconds per cycle)",
    "editor.bg_anim_intensity": "Intensity (opacity, 0-30%)",
    "editor.bg_anim_saturate": "Saturation (0.5 = pale, 1.5 = vivid)",
    "editor.bg_anim_colors": "Colours (4 stops)",
    "editor.bg_color_1": "Colour 1",
    "editor.bg_color_2": "Colour 2",
    "editor.bg_color_3": "Colour 3",
    "editor.bg_color_4": "Colour 4",
    "editor.group_sensors_display": "Sensors & Display",
    "editor.group_behavior": "Behavior",
    "editor.group_label_positions": "Watt label positions",
    "editor.solar_label_pos_solar_house": "Label: Solar → House",
    "editor.solar_label_pos_solar_grid": "Label: Solar → Grid (export)",
    "editor.grid_label_pos_import": "Label: Grid → House (import)",
    "editor.battery_label_pos": "Label: Battery ↔ House",
    "editor.venus_label_pos": "Label: Venus ↔ House",
    "editor.battery_soc_donut_section": "🍩 SoC donut (charge level ring)",
    "editor.battery_soc_donut_hint": "Shows the battery's state-of-charge as a ring around the bubble. Filled segment = current SoC in battery colour, rest grey. Like a smartphone battery indicator.",
    "editor.battery_soc_donut_enabled": "Enable SoC donut",
    "editor.venus_soc_donut_section": "🍩 SoC donut (charge level ring)",
    "editor.venus_soc_donut_hint": "Shows the Venus state-of-charge as a ring around the bubble. Filled segment = current SoC in Venus colour, rest grey.",
    "editor.venus_soc_donut_enabled": "Enable SoC donut",
    "editor.flow_rate_title": "Show Flow Rates (W) on pipes",
    "editor.pipe_label_size": "Pipe Label Font Size (px)",
    "editor.bubble_size": "Bubble size (px)",
    "editor.bubble_animation_threshold": "Animate above (W)",
    "editor.demo_mode": "Demo mode (1000W on all pipes)",
    "editor.card_offset_x": "Card horizontal offset (px)",
    "editor.card_offset_y": "Card vertical offset (px)",
    "editor.donut_section": "Donut Chart (Daily Mix)",
    "editor.donut_hint": "Shows the energy mix as a colored ring around the house bubble. When daily mode is enabled, the donut shows accumulated daily consumption in 4 segments (PV, LG, Venus, Grid) instead of the current live mix. Requires the \"Donut Chart\" toggle in Display & Options.",
    "editor.donut_today_mode": "Daily mode instead of live mode",
    "editor.donut_today_solar": "Daily sensor: PV → House (kWh)",
    "editor.donut_today_battery": "Daily sensor: LG → House (kWh)",
    "editor.donut_today_venus": "Daily sensor: Venus → House (kWh)",
    "editor.donut_today_grid": "Daily sensor: Grid → House (kWh)",
    "editor.consumer_enabled": "Consumer enabled",
    "editor.bubble_label_offset_x": "Watt label horizontal offset (px)",
    "editor.bubble_label_offset_y": "Watt label vertical offset (px)",
    "editor.consumer_show_power": "Show power instead of secondary sensor (big)",
    "editor.consumer_show_flow_rate": "Show watt value on pipe",
    "editor.consumer_label_offset_x": "Watt label horizontal offset (px)",
    "editor.consumer_label_offset_y": "Watt label vertical offset (px)",
    "editor.consumer_animation_threshold": "Animate above (W)",
    "editor.invert_battery": "Invert Power Value (+/-)",
    "editor.label_toggle": "Show Label in Bubble",
    "editor.compact_view": "Compact View (evcc)",
    "editor.compact_details": "Compact View Details",
    "editor.hide_inactive": "Hide Inactive Pipes",
    "editor.entity": "Combined Battery Sensor (W)",
    "editor.label": "Label",
    "editor.icon": "Icon",
    "editor.back": "Back",
    "editor.battery_soc_label": "State of Charge (%)",
    "editor.house_total_title": "🏠 Total Consumption (optional)",
    "editor.house_sensor_label": "Sensor for House Consumption (optional)",
    "editor.house_sensor_hint": "Required to make the house icon clickable (more-details). Otherwise, the house consumption is calculated.",
    "editor.consumer_1_title": "🚗 Left (Purple)",
    "editor.consumer_2_title": "♨️ Center (Orange)",
    "editor.consumer_3_title": "🏊 Right (Cyan)",
    "editor.zoom_label": "🔍 Zoom (Standard View)",
    "editor.transparent_background": "Hide card background",
    "editor.always_color_bubbles": "Always color bubbles (even at 0 W)",
    "editor.rotation_section": "🔄 Value rotation in bubble",
    "editor.rotation_hint": "Show extra daily counters in the bubble that alternate with the live value.",
    "editor.rotation_show_live": "Show live value (e.g. current power)",
    "editor.rotation_interval_sec": "Rotation interval (seconds)",
    "editor.rotation_show_slot_1": "Show daily counter 1",
    "editor.rotation_show_slot_2": "Show daily counter 2",
    "editor.rotation_show_slot_3": "Show daily counter 3",
    "editor.rotation_slot_1_sensor": "Daily counter 1 sensor",
    "editor.rotation_slot_2_sensor": "Daily counter 2 sensor",
    "editor.rotation_slot_3_sensor": "Daily counter 3 sensor",
    "editor.rotation_slot_1_color": "Daily counter 1 color",
    "editor.rotation_slot_2_color": "Daily counter 2 color",
    "editor.rotation_slot_3_color": "Daily counter 3 color",
    "editor.grid_donut_section": "🍩 Grid donut (today's mix)",
    "editor.grid_donut_hint": "Shows today's import-to-export ratio as a ring around the grid bubble. Import share in the grid color, export share in the export color.",
    "editor.grid_donut_enabled": "Enable today's donut",
    "editor.grid_donut_import_sensor": "Daily grid import sensor (kWh)",
    "editor.grid_donut_export_sensor": "Daily grid export sensor (kWh)",
    "editor.pv_donut_section": "🍩 PV donut (forecast remaining)",
    "editor.pv_donut_hint": "Shows how much of today's forecast is still expected (like a fuel gauge). Yellow segment = still to come, grey segment = already produced. Sensor should deliver the REMAINING forecast (e.g. evcc 'today.energy' which shrinks during the day).",
    "editor.pv_donut_enabled": "Enable forecast donut",
    "editor.pv_donut_produced_sensor": "Today's production sensor (kWh)",
    "editor.pv_donut_forecast_sensor": "Remaining forecast today (kWh)",
    "editor.neon_glow": "Neon Glow",
    "editor.donut_chart": "Donut Chart (Grid/House)",
    "editor.comet_tail": "Comet Tail Effect",
    "editor.dashed_line": "Dashed Line Effect",
    "editor.tinted_background": "Tinted Background in Bubbles",
    "editor.colored_values": "Colored Text Values",
    "editor.hide_consumer_icons": "Hide Consumer Icons",
    "editor.invert_consumer": "Invert Sensor Value (+/-)",
    "editor.hide_solar_arc": "Hide top solar pipe",
    "editor.storage_enabled": "Storage enabled",
    "editor.secondary_sensor": "Secondary Sensor (display only)",
    "editor.grid_to_battery_sensor": "Grid to Battery Sensor (W, optional)",
    "editor.grid_to_battery_hint": "Optional: separate sensor for grid-to-battery flow. If empty, the value is calculated automatically.",
    "editor.grid_combined_sensor": "Combined Grid Sensor (W, Optional)",
    "editor.grid_combined_hint": "Single sensor for import AND export: positive = import, negative = export. Overrides combined import/export sensor.",
    "editor.color_picker": "Bubble Color",
    "editor.pipe_color": "Pipe Color",
    "editor.export_color": "Export Color",
    "editor.consumer_unit_kw": "Sensor reports in kW",
    "editor.show_consumer_always": "Show Consumers at zero watts",
    "editor.battery_charge_sensor": "Battery Charge Sensor (W, Optional)",
    "editor.battery_discharge_sensor": "Battery Discharge Sensor (W, Optional)",
    "editor.battery_separate_hint": "Optional: Separate sensors for charge/discharge. Override the main sensor for calculations.",
    "editor.consumer_hide_pipe": "Hide pipe at low power",
    "editor.consumer_pipe_threshold": "Pipe Threshold (Watts)",
    "editor.text_color": "Text Color",
    "editor.icon_color": "Icon Color",
    "editor.secondary_color": "Secondary",
    "editor.battery_charge_via_house": "Battery charge via house consumption",
    "editor.battery_show_power": "Show power instead of SoC",
    "editor.solar_unit_kw": "Show Solar in kW",
    "editor.grid_unit_kw": "Show Grid in kW",
    "editor.battery_unit_kw": "Show Battery in kW",
    "editor.venus_entity": "Combined Venus Sensor (W, signed)",
    "editor.venus_soc_label": "Venus State of Charge (%)",
    "editor.venus_charge_sensor": "Venus Charge Sensor (W, Optional)",
    "editor.venus_discharge_sensor": "Venus Discharge Sensor (W, Optional)",
    "editor.venus_separate_hint": "Optional: Separate sensors for charge/discharge. Override the main sensor for calculations.",
    "editor.venus_charge_via_house": "Venus charge via house consumption",
    "editor.venus_show_power": "Show power instead of SoC (Venus)",
    "editor.venus_unit_kw": "Show Venus in kW",
    "editor.invert_venus": "Invert Power Value (+/-) for Venus",
    "editor.venus_secondary_sensor": "Secondary Sensor (display only) for Venus",
    "editor.consumer_4_title": "⚡ Row 2 Left (Yellow)",
    "editor.consumer_5_title": "💡 Row 2 Right (Indigo)",
    "editor.consumer_6_title": "💡 Row 2 Outer Left (Teal)",
    "editor.consumer_7_title": "💡 Row 2 Outer Right (Pink)",
  },
  card: {
    "card.label_solar": "Solar",
    "card.label_grid": "Grid",
    "card.label_battery": "Battery",
    "card.label_venus": "Venus",
    "card.label_house": "Consumption",
    "card.label_car": "Car",
    "card.label_heater": "Heater",
    "card.label_pool": "Pool",
    "card.label_consumer_4": "Cons. 4",
    "card.label_consumer_5": "Cons. 5",
    "editor.sparkline_title": "Sparkline (Background history graph)",
    "editor.sparkline_hint": "Shows the historical power trace as a mini chart in the bubble background. Data is pulled from HA history (refresh every 60 s).",
    "editor.sparkline_enabled": "Enable sparkline",
    "editor.sparkline_period": "Time window",
    "editor.sparkline_layer": "Layer (z-order)",
    "editor.sparkline_layer_back": "Back (behind donut)",
    "editor.sparkline_layer_mid": "Middle",
    "editor.sparkline_layer_front": "Front (above text)",
    "editor.sparkline_style": "Style",
    "editor.sparkline_style_area": "Area only",
    "editor.sparkline_style_line": "Line only",
    "editor.sparkline_style_arealine": "Area + line",
    "editor.sparkline_opacity": "Opacity",
    "editor.sparkline_color": "Color",
    "editor.sparkline_entity_label": "Sensor (optional)",
    "editor.sparkline_entity_hint": "Leave empty to use the bubble's main entity. Pick a different sensor (e.g. temperature, daily total) if you want to chart something other than power.",
    "editor.sparkline_debug": "Debug console output (DevTools)",
    "editor.sparkline_test_mode": "Test mode (synthetic sine data)",

    // Phase 5.68: LG charge-source mix ring (PV vs Grid)
    "editor.battery_mix_section": "Charge source (outer mix ring)",
    "editor.battery_mix_hint": "Adds a second ring around the SoC donut showing where LG's stored energy came from. For a storage bubble there are only 2 sources: PV and Grid.",
    "editor.battery_mix_enabled": "Enable charge-source ring",
    "editor.battery_mix_period": "Time period",
    "editor.battery_mix_period_day": "Day",
    "editor.battery_mix_period_month": "Month",
    "editor.battery_mix_period_year": "Year",
    "editor.battery_mix_gap": "Gap from SoC donut (px)",
    "editor.battery_mix_thickness": "Ring thickness (px)",
    "editor.battery_mix_day_section": "Daily sensors",
    "editor.battery_mix_month_section": "Monthly sensors",
    "editor.battery_mix_year_section": "Yearly sensors",
    "editor.battery_mix_pv_label": "PV → LG (kWh)",
    "editor.battery_mix_grid_label": "Grid → LG (kWh)",
  }
};
