export default {
  editor: {
    "card.label_import": "Import",
    "card.label_export": "Export",
    "editor.main_title": "Haupt Entitäten",
    "editor.solar_section": "Solar/PV",
    "editor.grid_section": "Netz Import/Export",
    "editor.battery_section": "Batterie 1",
    "editor.venus_section": "Batterie 2",
    "editor.consumer_1_section": "Tesla",
    "editor.consumers_section": "Haus",
    "editor.bubble_fallback": "Bubble {n}",
    "editor.consumer_1_donut_section": "SoC-Donut (innerer Ring)",
    "editor.consumer_1_donut_hint": "Zeigt den Wert des Zweitsensors als gefüllten Ring um die Bubble. Das Maximum legt fest, was 100% bedeutet (z.B. 100 für SoC %, 65 für Kessel-Temperatur in °C, 200 für Wasserstand in cm).",
    "editor.consumer_1_soc_donut_enable": "SoC-Donut aktivieren",
    "editor.consumer_1_soc_max": "Maximum (= 100% Füllung)",
    "editor.consumer_5_donut_section": "Temperatur-Donut (innerer Ring)",
    "editor.consumer_5_donut_hint": "Zeigt den Wert des Zweitsensors (z.B. Kesseltemperatur) als gefüllten Ring um die Bubble. Das Maximum legt fest, was 100% bedeutet -- typisch 65 °C für einen Brauchwasserkessel.",
    "editor.consumer_5_soc_donut_enable": "Temperatur-Donut aktivieren",
    "editor.consumer_5_soc_max": "Maximum °C (= 100% Füllung)",
    "editor.consumer_5_mix_section": "Lade-Mix-Ring (äußerer Ring)",
    "editor.consumer_5_mix_hint": "Zeigt einen zweiten Ring außen um die BWWP-Bubble. Vier Segmente (PV gelb / Batterie 1 lila / Batterie 2 violett / Netz rot) gewichtet nach dem Energie-Mix im gewählten Zeitraum. Sensoren als Tages-/Monats-/Jahres-kWh-Werte in HEIMDALL anlegen.",
    "editor.consumer_5_mix_enable": "Lade-Mix-Ring aktivieren",
    "editor.consumer_5_mix_pv_day": "PV-Anteil heute (kWh)",
    "editor.consumer_5_mix_lg_day": "Batterie 1-Anteil heute (kWh)",
    "editor.consumer_5_mix_venus_day": "Batterie 2-Anteil heute (kWh)",
    "editor.consumer_5_mix_grid_day": "Netz-Anteil heute (kWh)",
    "editor.consumer_5_mix_pv_month": "PV-Anteil Monat (kWh)",
    "editor.consumer_5_mix_lg_month": "Batterie 1-Anteil Monat (kWh)",
    "editor.consumer_5_mix_venus_month": "Batterie 2-Anteil Monat (kWh)",
    "editor.consumer_5_mix_grid_month": "Netz-Anteil Monat (kWh)",
    "editor.consumer_5_mix_pv_year": "PV-Anteil Jahr (kWh)",
    "editor.consumer_5_mix_lg_year": "Batterie 1-Anteil Jahr (kWh)",
    "editor.consumer_5_mix_venus_year": "Batterie 2-Anteil Jahr (kWh)",
    "editor.consumer_5_mix_grid_year": "Netz-Anteil Jahr (kWh)",
    "editor.consumer_7_donut_section": "Wasserstand-Donut (innerer Ring)",
    "editor.consumer_7_donut_hint": "Zeigt den Wert des Zweitsensors (z.B. Wasserstand im Regenschacht) als gefüllten Ring um die Bubble. Das Maximum legt fest, was 100% bedeutet -- typisch 165 cm für einen Standard-Regenschacht.",
    "editor.consumer_7_soc_donut_enable": "Wasserstand-Donut aktivieren",
    "editor.consumer_7_soc_max": "Maximum cm (= 100% Füllung)",
    "editor.consumer_7_mix_section": "Lade-Mix-Ring (äußerer Ring)",
    "editor.consumer_7_mix_hint": "Zeigt einen zweiten Ring außen um die Pumpe-Bubble. Vier Segmente (PV gelb / Batterie 1 lila / Batterie 2 violett / Netz rot) gewichtet nach dem Energie-Mix im gewählten Zeitraum. Sensoren als Tages-/Monats-/Jahres-kWh-Werte in HEIMDALL anlegen.",
    "editor.consumer_7_mix_enable": "Lade-Mix-Ring aktivieren",
    "editor.consumer_7_mix_pv_day": "PV-Anteil heute (kWh)",
    "editor.consumer_7_mix_lg_day": "Batterie 1-Anteil heute (kWh)",
    "editor.consumer_7_mix_venus_day": "Batterie 2-Anteil heute (kWh)",
    "editor.consumer_7_mix_grid_day": "Netz-Anteil heute (kWh)",
    "editor.consumer_7_mix_pv_month": "PV-Anteil Monat (kWh)",
    "editor.consumer_7_mix_lg_month": "Batterie 1-Anteil Monat (kWh)",
    "editor.consumer_7_mix_venus_month": "Batterie 2-Anteil Monat (kWh)",
    "editor.consumer_7_mix_grid_month": "Netz-Anteil Monat (kWh)",
    "editor.consumer_7_mix_pv_year": "PV-Anteil Jahr (kWh)",
    "editor.consumer_7_mix_lg_year": "Batterie 1-Anteil Jahr (kWh)",
    "editor.consumer_7_mix_venus_year": "Batterie 2-Anteil Jahr (kWh)",
    "editor.consumer_7_mix_grid_year": "Netz-Anteil Jahr (kWh)",
    "editor.consumer_2_donut_section": "Konfigurierbarer Donut (innerer Ring)",
    "editor.consumer_2_donut_hint": "Zeigt den Wert des Zweitsensors als gefüllten Ring um die Bubble. Frei einsetzbar -- z.B. Tagesverbrauch (Max 5 kWh), Restzeit-Minuten oder anderes Fortschrittsmaß. Das Maximum legt fest, was 100% bedeutet.",
    "editor.consumer_2_soc_donut_enable": "Donut aktivieren",
    "editor.consumer_2_soc_max": "Maximum (= 100% Füllung)",
    "editor.consumer_2_mix_section": "Lade-Mix-Ring (äußerer Ring)",
    "editor.consumer_2_mix_hint": "Zeigt einen zweiten Ring außen um die Waschen-Bubble. Vier Segmente (PV gelb / Batterie 1 lila / Batterie 2 violett / Netz rot) gewichtet nach dem Energie-Mix im gewählten Zeitraum. Sensoren als Tages-/Monats-/Jahres-kWh-Werte in HEIMDALL anlegen.",
    "editor.consumer_2_mix_enable": "Lade-Mix-Ring aktivieren",
    "editor.consumer_2_mix_pv_day": "PV-Anteil heute (kWh)",
    "editor.consumer_2_mix_lg_day": "Batterie 1-Anteil heute (kWh)",
    "editor.consumer_2_mix_venus_day": "Batterie 2-Anteil heute (kWh)",
    "editor.consumer_2_mix_grid_day": "Netz-Anteil heute (kWh)",
    "editor.consumer_2_mix_pv_month": "PV-Anteil Monat (kWh)",
    "editor.consumer_2_mix_lg_month": "Batterie 1-Anteil Monat (kWh)",
    "editor.consumer_2_mix_venus_month": "Batterie 2-Anteil Monat (kWh)",
    "editor.consumer_2_mix_grid_month": "Netz-Anteil Monat (kWh)",
    "editor.consumer_2_mix_pv_year": "PV-Anteil Jahr (kWh)",
    "editor.consumer_2_mix_lg_year": "Batterie 1-Anteil Jahr (kWh)",
    "editor.consumer_2_mix_venus_year": "Batterie 2-Anteil Jahr (kWh)",
    "editor.consumer_2_mix_grid_year": "Netz-Anteil Jahr (kWh)",
    "editor.consumer_3_donut_section": "Konfigurierbarer Donut (innerer Ring)",
    "editor.consumer_3_donut_hint": "Zeigt den Wert des Zweitsensors als gefüllten Ring um die Bubble. Frei einsetzbar -- z.B. Tagesverbrauch (Max 5 kWh), Restzeit-Minuten oder anderes Fortschrittsmaß. Das Maximum legt fest, was 100% bedeutet.",
    "editor.consumer_3_soc_donut_enable": "Donut aktivieren",
    "editor.consumer_3_soc_max": "Maximum (= 100% Füllung)",
    "editor.consumer_3_mix_section": "Lade-Mix-Ring (äußerer Ring)",
    "editor.consumer_3_mix_hint": "Zeigt einen zweiten Ring außen um die Trockner-Bubble. Vier Segmente (PV gelb / Batterie 1 lila / Batterie 2 violett / Netz rot) gewichtet nach dem Energie-Mix im gewählten Zeitraum. Sensoren als Tages-/Monats-/Jahres-kWh-Werte in HEIMDALL anlegen.",
    "editor.consumer_3_mix_enable": "Lade-Mix-Ring aktivieren",
    "editor.consumer_3_mix_pv_day": "PV-Anteil heute (kWh)",
    "editor.consumer_3_mix_lg_day": "Batterie 1-Anteil heute (kWh)",
    "editor.consumer_3_mix_venus_day": "Batterie 2-Anteil heute (kWh)",
    "editor.consumer_3_mix_grid_day": "Netz-Anteil heute (kWh)",
    "editor.consumer_3_mix_pv_month": "PV-Anteil Monat (kWh)",
    "editor.consumer_3_mix_lg_month": "Batterie 1-Anteil Monat (kWh)",
    "editor.consumer_3_mix_venus_month": "Batterie 2-Anteil Monat (kWh)",
    "editor.consumer_3_mix_grid_month": "Netz-Anteil Monat (kWh)",
    "editor.consumer_3_mix_pv_year": "PV-Anteil Jahr (kWh)",
    "editor.consumer_3_mix_lg_year": "Batterie 1-Anteil Jahr (kWh)",
    "editor.consumer_3_mix_venus_year": "Batterie 2-Anteil Jahr (kWh)",
    "editor.consumer_3_mix_grid_year": "Netz-Anteil Jahr (kWh)",
    "editor.consumer_4_donut_section": "Konfigurierbarer Donut (innerer Ring)",
    "editor.consumer_4_donut_hint": "Zeigt den Wert des Zweitsensors als gefüllten Ring um die Bubble. Frei einsetzbar -- z.B. Tagesverbrauch (Max 5 kWh), Restzeit-Minuten oder anderes Fortschrittsmaß. Das Maximum legt fest, was 100% bedeutet.",
    "editor.consumer_4_soc_donut_enable": "Donut aktivieren",
    "editor.consumer_4_soc_max": "Maximum (= 100% Füllung)",
    "editor.consumer_4_mix_section": "Lade-Mix-Ring (äußerer Ring)",
    "editor.consumer_4_mix_hint": "Zeigt einen zweiten Ring außen um die Spüler-Bubble. Vier Segmente (PV gelb / Batterie 1 lila / Batterie 2 violett / Netz rot) gewichtet nach dem Energie-Mix im gewählten Zeitraum. Sensoren als Tages-/Monats-/Jahres-kWh-Werte in HEIMDALL anlegen.",
    "editor.consumer_4_mix_enable": "Lade-Mix-Ring aktivieren",
    "editor.consumer_4_mix_pv_day": "PV-Anteil heute (kWh)",
    "editor.consumer_4_mix_lg_day": "Batterie 1-Anteil heute (kWh)",
    "editor.consumer_4_mix_venus_day": "Batterie 2-Anteil heute (kWh)",
    "editor.consumer_4_mix_grid_day": "Netz-Anteil heute (kWh)",
    "editor.consumer_4_mix_pv_month": "PV-Anteil Monat (kWh)",
    "editor.consumer_4_mix_lg_month": "Batterie 1-Anteil Monat (kWh)",
    "editor.consumer_4_mix_venus_month": "Batterie 2-Anteil Monat (kWh)",
    "editor.consumer_4_mix_grid_month": "Netz-Anteil Monat (kWh)",
    "editor.consumer_4_mix_pv_year": "PV-Anteil Jahr (kWh)",
    "editor.consumer_4_mix_lg_year": "Batterie 1-Anteil Jahr (kWh)",
    "editor.consumer_4_mix_venus_year": "Batterie 2-Anteil Jahr (kWh)",
    "editor.consumer_4_mix_grid_year": "Netz-Anteil Jahr (kWh)",
    "editor.consumer_6_donut_section": "Konfigurierbarer Donut (innerer Ring)",
    "editor.consumer_6_donut_hint": "Zeigt den Wert des Zweitsensors als gefüllten Ring um die Bubble. Frei einsetzbar -- z.B. Innentemperatur (Max 30 °C), Luftfeuchtigkeit (Max 100 %), CO2 (Max 2000 ppm) oder anderes Fortschrittsmaß. Das Maximum legt fest, was 100% bedeutet.",
    "editor.consumer_6_soc_donut_enable": "Donut aktivieren",
    "editor.consumer_6_soc_max": "Maximum (= 100% Füllung)",
    "editor.consumer_6_mix_section": "Lade-Mix-Ring (äußerer Ring)",
    "editor.consumer_6_mix_hint": "Zeigt einen zweiten Ring außen um die Klima-Bubble. Vier Segmente (PV gelb / Batterie 1 lila / Batterie 2 violett / Netz rot) gewichtet nach dem Energie-Mix im gewählten Zeitraum. Sensoren als Tages-/Monats-/Jahres-kWh-Werte in HEIMDALL anlegen.",
    "editor.consumer_6_mix_enable": "Lade-Mix-Ring aktivieren",
    "editor.consumer_6_mix_pv_day": "PV-Anteil heute (kWh)",
    "editor.consumer_6_mix_lg_day": "Batterie 1-Anteil heute (kWh)",
    "editor.consumer_6_mix_venus_day": "Batterie 2-Anteil heute (kWh)",
    "editor.consumer_6_mix_grid_day": "Netz-Anteil heute (kWh)",
    "editor.consumer_6_mix_pv_month": "PV-Anteil Monat (kWh)",
    "editor.consumer_6_mix_lg_month": "Batterie 1-Anteil Monat (kWh)",
    "editor.consumer_6_mix_venus_month": "Batterie 2-Anteil Monat (kWh)",
    "editor.consumer_6_mix_grid_month": "Netz-Anteil Monat (kWh)",
    "editor.consumer_6_mix_pv_year": "PV-Anteil Jahr (kWh)",
    "editor.consumer_6_mix_lg_year": "Batterie 1-Anteil Jahr (kWh)",
    "editor.consumer_6_mix_venus_year": "Batterie 2-Anteil Jahr (kWh)",
    "editor.consumer_6_mix_grid_year": "Netz-Anteil Jahr (kWh)",
    "editor.consumer_1_mix_section": "Lade-Mix-Ring (äußerer Ring)",
    "editor.consumer_1_mix_hint": "Zeigt einen zweiten Ring außen um die Bubble. Der Ring teilt sich in vier Segmente auf (PV gelb / Batterie 1 lila / Batterie 2 violett / Netz rot) gewichtet nach dem Energie-Mix im gewählten Zeitraum. Sensoren bitte als Tages-/Monats-/Jahres-kWh-Werte in HEIMDALL anlegen.",
    "editor.consumer_1_mix_enable": "Lade-Mix-Ring aktivieren",
    "editor.consumer_1_mix_period": "Zeitraum",
    "editor.consumer_1_mix_period_day": "Tag",
    "editor.consumer_1_mix_period_month": "Monat",
    "editor.consumer_1_mix_period_year": "Jahr",
    "editor.consumer_1_mix_ring_gap": "Abstand zum SoC-Ring (px)",
    "editor.consumer_1_mix_ring_thickness": "Dicke des Mix-Rings (px)",
    "editor.consumer_1_mix_pv_day": "PV-Anteil heute (kWh)",
    "editor.consumer_1_mix_lg_day": "Batterie 1-Anteil heute (kWh)",
    "editor.consumer_1_mix_venus_day": "Batterie 2-Anteil heute (kWh)",
    "editor.consumer_1_mix_grid_day": "Netz-Anteil heute (kWh)",
    "editor.consumer_1_mix_pv_month": "PV-Anteil Monat (kWh)",
    "editor.consumer_1_mix_lg_month": "Batterie 1-Anteil Monat (kWh)",
    "editor.consumer_1_mix_venus_month": "Batterie 2-Anteil Monat (kWh)",
    "editor.consumer_1_mix_grid_month": "Netz-Anteil Monat (kWh)",
    "editor.consumer_1_mix_pv_year": "PV-Anteil Jahr (kWh)",
    "editor.consumer_1_mix_lg_year": "Batterie 1-Anteil Jahr (kWh)",
    "editor.consumer_1_mix_venus_year": "Batterie 2-Anteil Jahr (kWh)",
    "editor.consumer_1_mix_grid_year": "Netz-Anteil Jahr (kWh)",
    "editor.options_section": "Darstellung & Optionen",
    "editor.group_sizing": "Größen & Position",
    "editor.background_padding_section": "Hintergrund-Padding (manuell)",
    "editor.background_padding_top": "Hintergrund-Padding oben (px)",
    "editor.background_padding_bottom": "Hintergrund-Padding unten (px)",
    "editor.background_padding_left": "Hintergrund-Padding links (px)",
    "editor.background_padding_right": "Hintergrund-Padding rechts (px)",
    "editor.group_appearance": "Erscheinungsbild",
    "editor.group_display": "Anzeige-Verhalten",
    "editor.group_debug": "Debug & Test",
    "editor.group_bg_anim": "Hintergrund-Animation",
    "editor.bg_anim_hint": "Sanfte animierte Farbverläufe im Karten-Hintergrund. Nur wirksam wenn Kartenhintergrund sichtbar ist. Respektiert 'Animationen reduzieren' im Betriebssystem.",
    "editor.bg_anim_style": "Animations-Stil",
    "editor.bg_anim_off": "Aus",
    "editor.bg_anim_aurora": "Aurora (treibende Farb-Blobs)",
    "editor.bg_anim_flow": "Slow Flow (sanfter Farbverlauf)",
    "editor.bg_anim_duration": "Geschwindigkeit (Sekunden pro Zyklus)",
    "editor.bg_anim_intensity": "Intensität (Deckkraft, 0-30%)",
    "editor.bg_anim_saturate": "Sättigung (0.5 = blass, 1.5 = kräftig)",
    "editor.bg_anim_colors": "Farben (4 Stops)",
    "editor.bg_color_1": "Farbe 1",
    "editor.bg_color_2": "Farbe 2",
    "editor.bg_color_3": "Farbe 3",
    "editor.bg_color_4": "Farbe 4",
    "editor.group_sensors_display": "Sensoren & Darstellung",
    "editor.group_behavior": "Verhalten",
    "editor.group_label_positions": "Position der Watt-Labels",
    "editor.solar_label_pos_solar_house": "Label: Solar → Haus",
    "editor.solar_label_pos_solar_grid": "Label: Solar → Netz (Einspeisung)",
    "editor.grid_label_pos_import": "Label: Netz → Haus (Bezug)",
    "editor.battery_label_pos": "Label: Batterie ↔ Haus",
    "editor.venus_label_pos": "Label: Venus ↔ Haus",
    "editor.battery_soc_donut_section": "🍩 SoC-Donut (Ladestands-Ring)",
    "editor.battery_soc_donut_hint": "Zeigt den Akku-Ladestand als Ring um die Bubble. Gefüllter Anteil = aktueller SoC in Batterie-Farbe, Rest grau. Wie eine Smartphone-Akku-Anzeige.",
    "editor.battery_soc_donut_enabled": "SoC-Donut aktivieren",
    "editor.venus_soc_donut_section": "🍩 SoC-Donut (Ladestands-Ring)",
    "editor.venus_soc_donut_hint": "Zeigt den Venus-Ladestand als Ring um die Bubble. Gefüllter Anteil = aktueller SoC in Venus-Farbe, Rest grau.",
    "editor.venus_soc_donut_enabled": "SoC-Donut aktivieren",
    "editor.flow_rate_title": "Flussraten (W) an Röhren anzeigen",
    "editor.pipe_label_size": "Schriftgröße der Watt-Labels (px)",
    "editor.bubble_size": "Bubble-Größe (px)",
    "editor.bubble_animation_threshold": "Animation erst ab (W)",
    "editor.demo_mode": "Demo-Modus (1000W an allen Pipes)",
    "editor.card_offset_x": "Card horizontal verschieben (px)",
    "editor.card_offset_y": "Card vertikal verschieben (px)",
    "editor.donut_section": "Donut-Chart (Tages-Mix)",
    "editor.donut_hint": "Zeigt den Energie-Mix als farbigen Ring um die Haus-Bubble. Bei aktiviertem Tagesmodus wird statt des aktuellen Live-Mix der kumulierte Tagesverbrauch in 4 Segmenten (PV, LG, Venus, Netz) dargestellt. Erfordert den Schalter \"Donut Chart\" in Darstellung & Optionen.",
    "editor.donut_today_mode": "Tagesmodus statt Live-Modus",
    "editor.donut_today_solar": "Tages-Sensor: PV → Haus (kWh)",
    "editor.donut_today_battery": "Tages-Sensor: LG → Haus (kWh)",
    "editor.donut_today_venus": "Tages-Sensor: Venus → Haus (kWh)",
    "editor.donut_today_grid": "Tages-Sensor: Netz → Haus (kWh)",
    "editor.consumer_enabled": "Verbraucher aktiv",
    "editor.bubble_label_offset_x": "Watt-Label horizontal verschieben (px)",
    "editor.bubble_label_offset_y": "Watt-Label vertikal verschieben (px)",
    "editor.consumer_show_power": "Zeige Leistung statt Zweitsensor (groß)",
    "editor.consumer_show_flow_rate": "Watt-Wert an Pipe anzeigen",
    "editor.consumer_label_offset_x": "Watt-Label horizontal verschieben (px)",
    "editor.consumer_label_offset_y": "Watt-Label vertikal verschieben (px)",
    "editor.consumer_animation_threshold": "Animation erst ab (W)",
    "editor.invert_battery": "Wert umkehren (+/-)",
    "editor.label_toggle": "Label im Kreis anzeigen",
    "editor.compact_view": "Kompakte Ansicht (evcc)",
    "editor.compact_details": "Details für Kompakte Ansicht",
    "editor.hide_inactive": "Inaktive Röhren ausblenden",
    "editor.entity": "Kombinierter Batterie Sensor (W)",
    "editor.label": "Beschriftung",
    "editor.icon": "Icon",
    "editor.back": "Zurück",
    "editor.battery_soc_label": "Ladestand (%)",
    "editor.house_total_title": "🏠 Gesamtverbrauch (optional)",
    "editor.house_sensor_label": "Sensor für Hausverbrauch (optional)",
    "editor.house_sensor_hint": "Wird benötigt, damit das Haus-Icon anklickbar ist (more-details). Ansonsten wird der Hausverbrauch berechnet.",
    "editor.consumer_1_title": "🚗 Links (Lila)",
    "editor.consumer_2_title": "♨️ Mitte (Orange)",
    "editor.consumer_3_title": "🏊 Rechts (Türkis)",
    "editor.zoom_label": "🔍 Zoom (Standard View)",
    "editor.transparent_background": "Karten-Hintergrund ausblenden",
    "editor.always_color_bubbles": "Bubbles immer farbig (auch bei 0 W)",
    "editor.rotation_section": "🔄 Wert-Rotation in Bubble",
    "editor.rotation_hint": "Zusätzliche Tageszähler in der Bubble anzeigen die abwechselnd mit dem Live-Wert eingeblendet werden.",
    "editor.rotation_show_live": "Live-Wert anzeigen (z.B. aktuelle Leistung)",
    "editor.rotation_interval_sec": "Wechsel-Intervall (Sekunden)",
    "editor.rotation_show_slot_1": "Tageszähler 1 anzeigen",
    "editor.rotation_show_slot_2": "Tageszähler 2 anzeigen",
    "editor.rotation_show_slot_3": "Tageszähler 3 anzeigen",
    "editor.rotation_slot_1_sensor": "Sensor Tageszähler 1",
    "editor.rotation_slot_2_sensor": "Sensor Tageszähler 2",
    "editor.rotation_slot_3_sensor": "Sensor Tageszähler 3",
    "editor.rotation_slot_1_color": "Farbe Tageszähler 1",
    "editor.rotation_slot_2_color": "Farbe Tageszähler 2",
    "editor.rotation_slot_3_color": "Farbe Tageszähler 3",
    "editor.grid_donut_section": "🍩 Netz-Donut (Tages-Mix)",
    "editor.grid_donut_hint": "Visualisiert das Verhältnis von Bezug zu Einspeisung des heutigen Tages als Ring um die Netz-Bubble. Bezug-Anteil in der Netz-Farbe, Einspeise-Anteil in der Export-Farbe.",
    "editor.grid_donut_enabled": "Tages-Donut aktivieren",
    "editor.grid_donut_import_sensor": "Sensor Netzbezug heute (kWh)",
    "editor.grid_donut_export_sensor": "Sensor Netzeinspeisung heute (kWh)",
    "editor.pv_donut_section": "🍩 PV-Donut (Rest-Forecast)",
    "editor.pv_donut_hint": "Zeigt wie viel vom Tages-Forecast noch zu erwarten ist (wie eine Tank-Anzeige). Gelber Anteil = noch erwartet, grauer Anteil = bereits erzeugt. Sensor liefert den Rest-Forecast (z.B. evcc 'today.energy' — der schrumpft im Tagesverlauf).",
    "editor.pv_donut_enabled": "Forecast-Donut aktivieren",
    "editor.pv_donut_produced_sensor": "Sensor heute erzeugt (kWh)",
    "editor.pv_donut_forecast_sensor": "Sensor Rest-Forecast heute (kWh)",
    "editor.neon_glow": "Neon Glow",
    "editor.donut_chart": "Donut Chart (Grid/Haus)",
    "editor.comet_tail": "Comet Tail Effect",
    "editor.dashed_line": "Dashed Line Effect",
    "editor.tinted_background": "Farbiger Hintergrund in Kreisen",
    "editor.colored_values": "Farbige Textwerte",
    "editor.hide_consumer_icons": "Icons unten ausblenden",
    "editor.invert_consumer": "Sensorwert invertieren (+/-)",
    "editor.hide_solar_arc": "Solar-Pipe (oben) ausblenden",
    "editor.storage_enabled": "Speicher aktiviert",
    "editor.secondary_sensor": "Zweiter Sensor (nur Anzeige)",
    "editor.grid_to_battery_sensor": "Netz-zu-Batterie Sensor (W, Optional)",
    "editor.grid_to_battery_hint": "Optional: separater Sensor für den Netz-zu-Batterie Fluss. Wenn leer, wird der Wert automatisch berechnet.",
    "editor.grid_combined_sensor": "Kombinierter Netz-Sensor (W, Optional)",
    "editor.grid_combined_hint": "Ein Sensor für Import UND Export: positiv = Import, negativ = Export. Überschreibt den kombinierten Import/Export Sensor.",
    "editor.color_picker": "Bubble",
    "editor.pipe_color": "Pipe",
    "editor.export_color": "Export",
    "editor.consumer_unit_kw": "Sensor meldet in kW",
    "editor.show_consumer_always": "Verbraucher bei null Watt anzeigen",
    "editor.battery_charge_sensor": "Batterie-Ladung Sensor (W, Optional)",
    "editor.battery_discharge_sensor": "Batterie-Entladung Sensor (W, Optional)",
    "editor.battery_separate_hint": "Optional: Separate Sensoren für Laden/Entladen. Überschreiben den Hauptsensor für die Berechnung.",
    "editor.consumer_hide_pipe": "Pipe bei geringer Leistung ausblenden",
    "editor.consumer_pipe_threshold": "Pipe-Schwellenwert (Watt)",
    "editor.text_color": "Text",
    "editor.icon_color": "Icon",
    "editor.secondary_color": "Secondary",
    "editor.battery_charge_via_house": "Batterie-Ladung über Hausverbrauch umleiten",
    "editor.battery_show_power": "Zeige Leistung statt SoC",
    "editor.solar_unit_kw": "Solar in kW anzeigen",
    "editor.grid_unit_kw": "Grid in kW anzeigen",
    "editor.battery_unit_kw": "Batterie in kW anzeigen",
    "editor.venus_entity": "Kombinierter Venus Sensor (W, signed)",
    "editor.venus_soc_label": "Venus Ladestand (%)",
    "editor.venus_charge_sensor": "Venus-Ladung Sensor (W, Optional)",
    "editor.venus_discharge_sensor": "Venus-Entladung Sensor (W, Optional)",
    "editor.venus_separate_hint": "Optional: Separate Sensoren für Laden/Entladen. Überschreiben den Hauptsensor für die Berechnung.",
    "editor.venus_charge_via_house": "Venus-Ladung über Hausverbrauch umleiten",
    "editor.venus_show_power": "Zeige Leistung statt SoC (Venus)",
    "editor.venus_unit_kw": "Venus in kW anzeigen",
    "editor.invert_venus": "Wert umkehren (+/-) für Venus",
    "editor.venus_secondary_sensor": "Zweiter Sensor (nur Anzeige) für Venus",
    "editor.consumer_4_title": "⚡ Reihe 2 Links (Gelb)",
    "editor.consumer_5_title": "💡 Reihe 2 Rechts (Indigo)",
    "editor.consumer_6_title": "💡 Reihe 2 Außen Links (Teal)",
    "editor.consumer_7_title": "💡 Reihe 2 Außen Rechts (Pink)",
  },
  card: {
    "card.label_solar": "Solar",
    "card.label_grid": "Netz",
    "card.label_battery": "Batterie",
    "card.label_venus": "Venus",
    "card.label_house": "Verbrauch",
    "card.label_car": "E-Auto",
    "card.label_heater": "Heizung",
    "card.label_pool": "Pool",
    "card.label_consumer_4": "Verbr. 4",
    "card.label_consumer_5": "Verbr. 5",
    "editor.sparkline_title": "Sparkline (Verlauf im Hintergrund)",
    "editor.sparkline_hint": "Zeigt den historischen Leistungsverlauf als Mini-Diagramm im Hintergrund der Bubble. Daten kommen aus der HA-History (Refresh alle 60 Sek.).",
    "editor.sparkline_enabled": "Sparkline aktivieren",
    "editor.sparkline_period": "Zeitraum",
    "editor.sparkline_layer": "Ebene (Z-Order)",
    "editor.sparkline_layer_back": "Ganz hinten (hinter Donut)",
    "editor.sparkline_layer_mid": "Mittlere Ebene",
    "editor.sparkline_layer_front": "Ganz vorne (über Text)",
    "editor.sparkline_style": "Darstellung",
    "editor.sparkline_style_area": "Nur Fläche",
    "editor.sparkline_style_line": "Nur Linie",
    "editor.sparkline_style_arealine": "Fläche + Linie",
    "editor.sparkline_opacity": "Transparenz",
    "editor.sparkline_color": "Farbe",
    "editor.sparkline_entity_label": "Sensor (optional)",
    "editor.sparkline_entity_hint": "Wenn leer, wird der Hauptsensor der Bubble verwendet. Wähle einen anderen Sensor (z.B. Temperatur, Tagesverbrauch), wenn Du etwas anderes als Leistung im Verlauf sehen möchtest.",
    "editor.sparkline_debug": "Debug-Konsolen-Ausgabe (DevTools)",
  }
};
