export default {
  editor: {
    "card.label_import": "Import",
    "card.label_export": "Export",
    "editor.main_title": "Haupt Entitäten",
    "editor.solar_section": "Solar/PV",
    "editor.grid_section": "Netz Import/Export",
    "editor.battery_section": "Batterie",
    "editor.venus_section": "Venus (2. Batterie)",
    "editor.consumers_section": "Zusätzliche Verbraucher",
    "editor.options_section": "Darstellung & Optionen",
    "editor.flow_rate_title": "Flussraten (W) an Röhren anzeigen",
    "editor.pipe_label_size": "Schriftgröße der Watt-Labels (px)",
    "editor.bubble_animation_threshold": "Animation erst ab (W)",
    "editor.demo_mode": "Demo-Modus (1000W an allen Pipes)",
    "editor.card_offset_x": "Card horizontal verschieben (px)",
    "editor.card_offset_y": "Card vertikal verschieben (px)",
    "editor.donut_section": "Donut-Chart (Tages-Mix)",
    "editor.donut_hint": "Zeigt den Energie-Mix als farbigen Ring um die Haus-Bubble. Bei aktiviertem Tagesmodus wird statt des aktuellen Live-Mix der kumulierte Tagesverbrauch in 4 Segmenten (PV, LG, Venus, Netz) dargestellt. Erfordert den Schalter \"Donut Chart\" in Darstellung & Optionen.",
    "editor.donut_today_mode": "Tagesmodus statt Live-Modus",
    "editor.donut_today_solar": "Tages-Sensor: PV → Haus (kWh)",
    "editor.donut_today_battery": "Tages-Sensor: LG → Haus (kWh)",
    "editor.donut_today_venus": "Tages-Sensor: Venus → Haus (kWh)",
    "editor.donut_today_grid": "Tages-Sensor: Netz → Haus (kWh)",
    "editor.consumer_enabled": "Verbraucher aktiv",
    "editor.bubble_label_offset_x": "Watt-Label horizontal verschieben (px)",
    "editor.bubble_label_offset_y": "Watt-Label vertikal verschieben (px)",
    "editor.consumer_show_power": "Zeige Leistung statt Zweitsensor (groß)",
    "editor.consumer_show_flow_rate": "Watt-Wert an Pipe anzeigen",
    "editor.consumer_label_offset_x": "Watt-Label horizontal verschieben (px)",
    "editor.consumer_label_offset_y": "Watt-Label vertikal verschieben (px)",
    "editor.consumer_animation_threshold": "Animation erst ab (W)",
    "editor.invert_battery": "Wert umkehren (+/-)",
    "editor.label_toggle": "Label im Kreis anzeigen",
    "editor.compact_view": "Kompakte Ansicht (evcc)",
    "editor.compact_details": "Details für Kompakte Ansicht",
    "editor.hide_inactive": "Inaktive Röhren ausblenden",
    "editor.entity": "Kombinierter Batterie Sensor (W)",
    "editor.label": "Beschriftung",
    "editor.icon": "Icon",
    "editor.back": "Zurück",
    "editor.battery_soc_label": "Ladestand (%)",
    "editor.house_total_title": "🏠 Gesamtverbrauch (optional)",
    "editor.house_sensor_label": "Sensor für Hausverbrauch (optional)",
    "editor.house_sensor_hint": "Wird benötigt, damit das Haus-Icon anklickbar ist (more-details). Ansonsten wird der Hausverbrauch berechnet.",
    "editor.consumer_1_title": "🚗 Links (Lila)",
    "editor.consumer_2_title": "♨️ Mitte (Orange)",
    "editor.consumer_3_title": "🏊 Rechts (Türkis)",
    "editor.zoom_label": "🔍 Zoom (Standard View)",
    "editor.neon_glow": "Neon Glow",
    "editor.donut_chart": "Donut Chart (Grid/Haus)",
    "editor.comet_tail": "Comet Tail Effect",
    "editor.dashed_line": "Dashed Line Effect",
    "editor.tinted_background": "Farbiger Hintergrund in Kreisen",
    "editor.colored_values": "Farbige Textwerte",
    "editor.hide_consumer_icons": "Icons unten ausblenden",
    "editor.invert_consumer": "Sensorwert invertieren (+/-)",
    "editor.hide_solar_arc": "Solar-Pipe (oben) ausblenden",
    "editor.storage_enabled": "Speicher aktiviert",
    "editor.secondary_sensor": "Zweiter Sensor (nur Anzeige)",
    "editor.grid_to_battery_sensor": "Netz-zu-Batterie Sensor (W, Optional)",
    "editor.grid_to_battery_hint": "Optional: separater Sensor für den Netz-zu-Batterie Fluss. Wenn leer, wird der Wert automatisch berechnet.",
    "editor.grid_combined_sensor": "Kombinierter Netz-Sensor (W, Optional)",
    "editor.grid_combined_hint": "Ein Sensor für Import UND Export: positiv = Import, negativ = Export. Überschreibt den kombinierten Import/Export Sensor.",
    "editor.color_picker": "Bubble",
    "editor.pipe_color": "Pipe",
    "editor.export_color": "Export",
    "editor.consumer_unit_kw": "Sensor meldet in kW",
    "editor.show_consumer_always": "Verbraucher bei null Watt anzeigen",
    "editor.battery_charge_sensor": "Batterie-Ladung Sensor (W, Optional)",
    "editor.battery_discharge_sensor": "Batterie-Entladung Sensor (W, Optional)",
    "editor.battery_separate_hint": "Optional: Separate Sensoren für Laden/Entladen. Überschreiben den Hauptsensor für die Berechnung.",
    "editor.consumer_hide_pipe": "Pipe bei geringer Leistung ausblenden",
    "editor.consumer_pipe_threshold": "Pipe-Schwellenwert (Watt)",
    "editor.text_color": "Text",
    "editor.icon_color": "Icon",
    "editor.secondary_color": "Secondary",
    "editor.battery_charge_via_house": "Batterie-Ladung über Hausverbrauch umleiten",
    "editor.battery_show_power": "Zeige Leistung statt SoC",
    "editor.solar_unit_kw": "Solar in kW anzeigen",
    "editor.grid_unit_kw": "Grid in kW anzeigen",
    "editor.battery_unit_kw": "Batterie in kW anzeigen",
    "editor.venus_entity": "Kombinierter Venus Sensor (W, signed)",
    "editor.venus_soc_label": "Venus Ladestand (%)",
    "editor.venus_charge_sensor": "Venus-Ladung Sensor (W, Optional)",
    "editor.venus_discharge_sensor": "Venus-Entladung Sensor (W, Optional)",
    "editor.venus_separate_hint": "Optional: Separate Sensoren für Laden/Entladen. Überschreiben den Hauptsensor für die Berechnung.",
    "editor.venus_charge_via_house": "Venus-Ladung über Hausverbrauch umleiten",
    "editor.venus_show_power": "Zeige Leistung statt SoC (Venus)",
    "editor.venus_unit_kw": "Venus in kW anzeigen",
    "editor.invert_venus": "Wert umkehren (+/-) für Venus",
    "editor.venus_secondary_sensor": "Zweiter Sensor (nur Anzeige) für Venus",
    "editor.consumer_4_title": "⚡ Reihe 2 Links (Gelb)",
    "editor.consumer_5_title": "💡 Reihe 2 Rechts (Indigo)",
    "editor.consumer_6_title": "💡 Reihe 2 Außen Links (Teal)",
    "editor.consumer_7_title": "💡 Reihe 2 Außen Rechts (Pink)",
  },
  card: {
    "card.label_solar": "Solar",
    "card.label_grid": "Netz",
    "card.label_battery": "Batterie",
    "card.label_venus": "Venus",
    "card.label_house": "Verbrauch",
    "card.label_car": "E-Auto",
    "card.label_heater": "Heizung",
    "card.label_pool": "Pool",
    "card.label_consumer_4": "Verbr. 4",
    "card.label_consumer_5": "Verbr. 5",
  }
};
